//! Shared, IO-free domain types for Bhippi.

#![forbid(unsafe_code)]

mod computer;
mod design;
mod domain;
mod engine;
mod error;
mod events;
mod ids;
mod inspect;

pub use computer::{
    ComputerActionClass, ComputerOutcome, ComputerScope, COMPUTER_DRAG_DURATION_MS,
    COMPUTER_MAX_ACTIONS_PER_TURN, COMPUTER_MAX_PATH_DURATION_MS, COMPUTER_MAX_PATH_POINTS,
    COMPUTER_MAX_REASON_CHARS, COMPUTER_MAX_REPAIRS, COMPUTER_MAX_WAIT_MS, COMPUTER_PATH_SAMPLE_MS,
    COMPUTER_SETTLE_INTERVAL_MS, COMPUTER_SETTLE_TIMEOUT_MS, COMPUTER_VERBATIM_ROUNDS,
};
pub use design::{
    DesignSurface, DESIGN_CONTEXT_TOKEN_BUDGET, DESIGN_INDEX_TOKEN_BUDGET,
    DESIGN_LESSONS_MAX_APPROVED, DESIGN_LESSON_MAX_RULE_BYTES, DESIGN_LESSON_MIN_EVIDENCE,
    DESIGN_LESSON_TOKEN_BUDGET, DESIGN_MAX_SECTIONS_PER_TURN, DESIGN_MEMORY_TOKEN_BUDGET,
    DESIGN_QUERY_ANSWER_TOKEN_BUDGET, DESIGN_QUERY_MAX_ROUNDS, DESIGN_SEARCH_MAX_HITS,
    TASTE_PROFILE_MAX_PINS, TASTE_PROFILE_TOKEN_BUDGET,
};
pub use domain::{Origin, TaskClass};
pub use engine::{
    EngineActor, EngineEvent, EngineLogLevel, EngineTransactionSummary, EntityTransformPatch,
    PlayState, ASSET_PREVIEW_START_TIMEOUT_SECS, ENGINE_AUTONOMY_MAX_ROUNDS,
    ENGINE_AUTONOMY_MAX_STALLED_ROUNDS, ENGINE_CONTEXT_TOKEN_BUDGET,
    ENGINE_GAME_DEBUG_RETAINED_RUNS, ENGINE_OBSERVATION_TIMEOUT_SECS,
    ENGINE_PLAYTEST_FIXED_DELTA_SECONDS, ENGINE_PLAYTEST_MAX_FRAMES_PER_STEP,
    ENGINE_PLAYTEST_MAX_KEYS_PER_STEP, ENGINE_PLAYTEST_MAX_KEY_CODE_BYTES,
    ENGINE_PLAYTEST_MAX_STEPS, ENGINE_SCREENSHOT_MAX_BYTES, ENGINE_SCREENSHOT_MAX_DIMENSION,
    WORKSPACE_IMAGE_MAX_BYTES, WORKSPACE_MODEL_MAX_BYTES, WORKSPACE_TOOL_MAX_FILE_BYTES,
};
pub use error::{BhippiError, BudgetScope, FetchErrorKind, GateName};
pub use events::{Capability, ErrorCode, Event, Health, ResyncReason, Timestamp};
pub use ids::{
    AssetId, BuildId, DotId, EntityId, FileId, GameId, ImageId, ModuleId, NodeId, PostId,
    ProjectId, ProviderId, SceneId, SessionId, SkillId, SourceId, SymbolId, TickerEventId,
    TransactionId,
};
pub use inspect::{
    health_penalty, FindingStatus, FixRisk, InspectorId, Severity, INSPECT_BLEND_TIME_FLOOR,
    INSPECT_CONFIDENCE_CERTAIN, INSPECT_CONFIDENCE_HEURISTIC, INSPECT_CONTRAST_FLOOR,
    INSPECT_HEALTH_MAX, INSPECT_MAX_EVIDENCE, INSPECT_MAX_FINDINGS, INSPECT_MAX_FIX_ACTIONS,
    INSPECT_MAX_HASH_BYTES, INSPECT_MAX_SCENES, INSPECT_MAX_SCRIPTS, INSPECT_MAX_SCRIPT_BYTES,
    INSPECT_MESH_LARGE_BYTES, INSPECT_MIN_CONFIDENCE, INSPECT_TEXTURE_LARGE_BYTES,
    INSPECT_TEXTURE_LARGE_PIXELS,
};

/// The result type shared across Bhippi library crates.
pub type Result<T> = std::result::Result<T, BhippiError>;
