// @ts-nocheck
type Value = any;

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Scaffolds a new game into the active project and reports the result. With no folder
	 *  name the manifest is written at the project root; otherwise into `<root>/<name>`
	 *  (non-game projects keep their code and game side by side).
	 */
	engineCreateGameManifest: (folderName: string | null, force: boolean) => typedError<EngineStatus, AppError>(__TAURI_INVOKE("engine_create_game_manifest", { folderName, force })),
	engineQueryScene: (scene: string | null) => typedError<EngineSceneQuery, AppError>(__TAURI_INVOKE("engine_query_scene", { scene })),
	// `scene.get(id)` — summary of a scene via the SEC 7.4 engine query API.
	engineQuerySceneView: (scene: string | null, deep: boolean) => typedError<EngineQuerySceneView, AppError>(__TAURI_INVOKE("engine_query_scene_view", { scene, deep })),
	// `scene.get_entity(id)` — one entity projection (compact or deep).
	engineQueryEntity: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	id: EntityId,
	name: string,
	parent: EntityId | null,
	tags: string[],
	stable_path: string,
	component_names: string[],
	components: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_entity", { scene, entityId, deep })),
	// `scene.find_entities(query)` — entities matching a filter.
	engineQueryFindEntities: (scene: string | null, filter: EntityQuery, deep: boolean) => typedError<EngineQueryEntityRef[], AppError>(__TAURI_INVOKE("engine_query_find_entities", { scene, filter, deep })),
	// `scene.get_components(id)` — component names, plus payloads in deep mode.
	engineQueryComponents: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	names: string[],
	payloads: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_components", { scene, entityId, deep })),
	// `scene.get_children(id)` — immediate children (entries in deep mode).
	engineQueryChildren: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	ids: EntityId[],
	entries: EngineQueryEntityRef[] | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_children", { scene, entityId, deep })),
	// `scene.get_parent(id)` — the parent (with component payloads in deep mode).
	engineQueryParent: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	parent: EngineQueryEntityRef | null,
	parent_components: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_parent", { scene, entityId, deep })),
	// `scene.get_scripts(id)` — the entity's `ScriptRef` binding.
	engineQueryScripts: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	script: string | null,
	hooks: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
	config: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_scripts", { scene, entityId, deep })),
	// `scene.get_asset_users(asset_id)` — entities whose components reference the asset.
	engineQueryAssetUsers: (scene: string | null, assetId: AssetId, deep: boolean) => typedError<EngineQueryAssetUsersView, AppError>(__TAURI_INVOKE("engine_query_asset_users", { scene, assetId, deep })),
	// `scene.get_asset_dependencies(asset_id)` — assets that ship alongside this one.
	engineQueryAssetDependencies: (scene: string | null, assetId: AssetId, deep: boolean) => typedError<EngineQueryAssetDependenciesView, AppError>(__TAURI_INVOKE("engine_query_asset_dependencies", { scene, assetId, deep })),
	// `scene.get_material_graph(material_id)` — material users + co-shipped textures.
	engineQueryMaterialGraph: (scene: string | null, materialId: AssetId, deep: boolean) => typedError<EngineQueryMaterialGraphView, AppError>(__TAURI_INVOKE("engine_query_material_graph", { scene, materialId, deep })),
	// `scene.get_shader(shader_id)` — shader users.
	engineQueryShader: (scene: string | null, shaderId: AssetId, deep: boolean) => typedError<EngineQueryShaderView, AppError>(__TAURI_INVOKE("engine_query_shader", { scene, shaderId, deep })),
	// `scene.get_animation_graph(id)` — the entity's animation clip + mesh + co-references.
	engineQueryAnimationGraph: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	clip: AssetId | null,
	clip_record: AssetRecord | null,
	mesh: AssetId | null,
	co_referenced: AssetId[],
} | null, AppError>(__TAURI_INVOKE("engine_query_animation_graph", { scene, entityId, deep })),
	// `scene.get_physics(id)` — the physics projection (ADR-0026).
	engineQueryPhysics: (scene: string | null, entityId: EntityId, deep: boolean) => typedError<{
	entity: EntityId,
	body_kind: string | null,
	mass: number | null,
	lock_rotation: boolean | null,
	collider_shape: string | null,
	sensor: boolean | null,
	has_character_controller: boolean,
	extras: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
} | null, AppError>(__TAURI_INVOKE("engine_query_physics", { scene, entityId, deep })),
	engineRecordConsole: (level: string, channel: string, text: string) => typedError<null, AppError>(__TAURI_INVOKE("engine_record_console", { level, channel, text })),
	engineRecordConsoleSource: (level: string, channel: string, text: string, file: string, line: number) => typedError<null, AppError>(__TAURI_INVOKE("engine_record_console_source", { level, channel, text, file, line })),
	engineConsoleRows: (level: string | null, channel: string | null, search: string | null, offset: number, limit: number) => typedError<EngineConsoleRow[], AppError>(__TAURI_INVOKE("engine_console_rows", { level, channel, search, offset, limit })),
	engineRecordPlayStats: (stats: EnginePlayStats) => typedError<null, AppError>(__TAURI_INVOKE("engine_record_play_stats", { stats })),
	engineClearPlayStats: () => typedError<null, AppError>(__TAURI_INVOKE("engine_clear_play_stats")),
	/**
	 *  Apply one action as the **user** (the editor's own edits: Add, Delete, Duplicate,
	 *  Inspector fields, weather). Journaled like every other transaction.
	 */
	engineApplyAction: (actionJson: string, scene: string | null, label: string | null) => typedError<EngineEditResult, AppError>(__TAURI_INVOKE("engine_apply_action", { actionJson, scene, label })),
	// Apply a batch of actions as one transaction, one journal row, one undo step.
	engineApplyBatch: (label: string, actionsJson: string, scene: string | null) => typedError<EngineBatchResult, AppError>(__TAURI_INVOKE("engine_apply_batch", { label, actionsJson, scene })),
	/**
	 *  How much the agent may change without asking (ENG-116). `ask` shows a plan card for
	 *  every change, `auto` (the default) asks only before deletions, `autonomous` never asks.
	 */
	enginePermissionMode: () => typedError<string, AppError>(__TAURI_INVOKE("engine_permission_mode")),
	setEnginePermissionMode: (mode: string) => typedError<null, AppError>(__TAURI_INVOKE("set_engine_permission_mode", { mode })),
	// Read this project's agent capability policy, for the settings panel and the prompt.
	engineAgentCapabilities: () => typedError<EngineCapabilityRow[], AppError>(__TAURI_INVOKE("engine_agent_capabilities")),
	/**
	 *  Change one capability and write it back to `Bhippi.game.toml` (ENG-190).
	 * 
	 *  The manifest is rewritten from the parsed document, so a hand-added comment elsewhere in
	 *  the file is lost — which is why this is the only writer, and why the panel says the file
	 *  is the source of truth.
	 */
	engineSetAgentCapability: (capability: string, decision: string) => typedError<EngineCapabilityRow[], AppError>(__TAURI_INVOKE("engine_set_agent_capability", { capability, decision })),
	/**
	 *  Undo one journalled change as a single operation (ENG-189).
	 * 
	 *  The unit is the transaction, and a batch is already one transaction (ENG-111), so
	 *  "undo everything the agent just did" is one row here rather than N presses of Ctrl+Z.
	 *  It works across restarts because the inverse comes from the journal rather than from the
	 *  in-memory undo stack.
	 * 
	 *  The revert is applied as a **new** transaction by the user, so it is itself undoable and
	 *  appears in the history — reverting is a decision, and decisions get taken back too.
	 */
	engineUndoJournalled: (txnId: string) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_undo_journalled", { txnId })),
	/**
	 *  Open a scene into the session store and return its state. Opening twice is free — the
	 *  second call returns the live document, unsaved edits included.
	 */
	engineOpenScene: (scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_open_scene", { scene })),
	/**
	 *  Throw away the in-memory document and re-read the file. The escape hatch when the scene
	 *  changed underneath an open session and the user chooses "Take disk" (ENG-108).
	 */
	engineReloadScene: (scene: string) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_reload_scene", { scene })),
	// Return both conflict sides without mutating either one (ENG-108 Diff).
	engineSceneDiff: (scene: string) => typedError<EngineSceneDiff, AppError>(__TAURI_INVOKE("engine_scene_diff", { scene })),
	/**
	 *  Replay the validated crash snapshot into the live session. The authored file remains
	 *  untouched until Save, so recovery itself is reversible by choosing Take disk.
	 */
	engineRecoverScene: (scene: string) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_recover_scene", { scene })),
	/**
	 *  Close a scene. A dirty scene refuses unless `discard` is set, so no stray navigation
	 *  can silently lose work.
	 */
	engineCloseScene: (scene: string, discard: boolean) => typedError<null, AppError>(__TAURI_INVOKE("engine_close_scene", { scene, discard })),
	engineSaveScene: (scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_save_scene", { scene })),
	engineSaveAll: () => typedError<string[], AppError>(__TAURI_INVOKE("engine_save_all")),
	/**
	 *  Undo the last transaction on a scene — user edits and agent batches share one stack, so
	 *  Ctrl+Z reverses "what the AI just did" exactly like it reverses a drag.
	 */
	engineUndo: (scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_undo", { scene })),
	engineRedo: (scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_redo", { scene })),
	/**
	 *  Start an interactive edit. A gizmo drag calls this once, records while dragging, and
	 *  commits on release — one undo entry for the whole drag (ENG-102).
	 */
	engineBeginInteraction: (scene: string | null, label: string) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_begin_interaction", { scene, label })),
	engineRecordInteraction: (actionJson: string, scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_record_interaction", { actionJson, scene })),
	engineCommitInteraction: (scene: string | null) => typedError<{
	scene_path: string,
	txn_id: string,
	// `user` | `agent`
	actor: string,
	label: string,
	summary: string,
	op_count: number,
	touched: EntityId[],
	state: EngineSceneState,
	/**
	 *  Set when the transaction was journaled; `None` means the journal was unavailable
	 *  (the edit still applied — the ledger is a record, not a gate).
	 */
	revision: number | null,
} | null, AppError>(__TAURI_INVOKE("engine_commit_interaction", { scene })),
	engineCancelInteraction: (scene: string | null) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_cancel_interaction", { scene })),
	engineSetSelection: (scene: string | null, selection: EntityId[]) => typedError<EngineSceneState, AppError>(__TAURI_INVOKE("engine_set_selection", { scene, selection })),
	/**
	 *  The journal for this game, newest first. This is the honest answer to "what did the
	 *  agent change?" (INV-071) and it outlives the process.
	 */
	engineHistory: (scene: string | null, limit: number | null) => typedError<EngineHistoryEntry[], AppError>(__TAURI_INVOKE("engine_history", { scene, limit })),
	/**
	 *  The weather presets, straight from the engine registry — the picker renders this
	 *  instead of keeping its own copy of the numbers (ENG-105).
	 */
	engineWeatherPresets: () => typedError<WeatherPreset[], AppError>(__TAURI_INVOKE("engine_weather_presets")),
	engineTemplates: () => typedError<EngineTemplateView[], AppError>(__TAURI_INVOKE("engine_templates")),
	/**
	 *  Compose the playable world for a scene. Play on **Main** runs the whole game; play on a
	 *  level runs that map plus the HUD; opening the HUD alone plays nothing but itself, so its
	 *  widgets can be rearranged without a level in the way.
	 */
	enginePlayWorld: (scene: string | null) => typedError<EnginePlayWorld, AppError>(__TAURI_INVOKE("engine_play_world", { scene })),
	/**
	 *  Run the content gates over the whole game (ENG-128).
	 * 
	 *  The same checks the build runs, surfaced before someone tries to build: a level named in
	 *  the manifest that is not on disk, a HUD path that does not resolve, an invented weather
	 *  id, a component pointing at an asset that was never imported.
	 */
	engineCheckContent: (release: boolean) => typedError<GateReport, AppError>(__TAURI_INVOKE("engine_check_content", { release })),
	/**
	 *  The component registry, as the Details panel and the Add Component menu render it.
	 * 
	 *  One source of truth: the same `schema::registry()` the validator uses, so a field the
	 *  panel offers is a field the engine will accept, and a component the menu lists is one
	 *  that exists (ENG-142).
	 */
	engineComponentSchema: () => typedError<EngineComponentView[], AppError>(__TAURI_INVOKE("engine_component_schema")),
	engineListAssets: () => typedError<EngineAssetView[], AppError>(__TAURI_INVOKE("engine_list_assets")),
	// Resolve every mesh and material the open scene references (ENG-160/162).
	engineRenderManifest: (scene: string | null) => typedError<RenderManifest, AppError>(__TAURI_INVOKE("engine_render_manifest", { scene })),
	engineSubmitScreenshot: (requestId: string, imageBase64: string, width: number, height: number) => typedError<null, AppError>(__TAURI_INVOKE("engine_submit_screenshot", { requestId, imageBase64, width, height })),
	engineSubmitPlaytest: (requestId: string, report: string) => typedError<null, AppError>(__TAURI_INVOKE("engine_submit_playtest", { requestId, report })),
	engineSubmitGameTestBatch: (requestId: string, report: string) => typedError<null, AppError>(__TAURI_INVOKE("engine_submit_game_test_batch", { requestId, report })),
	// Open the game's HUD document for editing.
	hudOpen: (path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_open", { path })),
	// Apply one HUD edit. Both the Details panel and the AI come through here.
	hudApply: (actionJson: string, path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_apply", { actionJson, path })),
	// Apply a whole form as one undo step.
	hudApplyMany: (actionsJson: string, label: string, path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_apply_many", { actionsJson, label, path })),
	hudUndo: (path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_undo", { path })),
	hudRedo: (path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_redo", { path })),
	hudSave: (path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_save", { path })),
	hudReload: (path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_reload", { path })),
	hudSelect: (widget: string | null, path: string | null) => typedError<HudState, AppError>(__TAURI_INVOKE("hud_select", { widget, path })),
	// The widget catalog the Add menu and the Details panel render from.
	hudWidgetCatalog: () => typedError<HudWidgetKindView[], AppError>(__TAURI_INVOKE("hud_widget_catalog")),
	getAppStatus: () => typedError<AppStatus, AppError>(__TAURI_INVOKE("get_app_status")),
	getEngineStatus: () => typedError<EngineStatus, AppError>(__TAURI_INVOKE("get_engine_status")),
	listPlugins: () => typedError<PluginMetadata[], AppError>(__TAURI_INVOKE("list_plugins")),
	activatePlugin: (pluginId: string) => typedError<null, AppError>(__TAURI_INVOKE("activate_plugin", { pluginId })),
	deactivatePlugin: (pluginId: string) => typedError<null, AppError>(__TAURI_INVOKE("deactivate_plugin", { pluginId })),
	/**
	 *  Installs a catalogue entry by id, or any other reference as a URL-backed plugin.
	 *  The user's click on Install **is** the permission for this.
	 */
	installPlugin: (pluginUrl: string) => typedError<null, AppError>(__TAURI_INVOKE("install_plugin", { pluginUrl })),
	// Removes a plugin. Built-ins refuse — they switch off instead.
	uninstallPlugin: (pluginId: string) => typedError<null, AppError>(__TAURI_INVOKE("uninstall_plugin", { pluginId })),
	// Moves an installed plugin up to the catalogue's version.
	updatePlugin: (pluginId: string) => typedError<null, AppError>(__TAURI_INVOKE("update_plugin", { pluginId })),
	/**
	 *  Re-detects every catalogued backend and rebuilds the runtime, keeping the user's
	 *  toggle prefs intact. Emits `providers-changed` when it lands.
	 */
	rescanProviders: () => typedError<null, AppError>(__TAURI_INVOKE("rescan_providers")),
	// Flips one provider's toggle, persists it in `config.toml`, and rebuilds the runtime.
	setProviderEnabled: (providerId: string, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_provider_enabled", { providerId, enabled })),
	/**
	 *  Runs the catalogue's install recipe for one CLI provider, streaming progress events.
	 *  The user's explicit click **is** the permission for this consequential action.
	 */
	installProvider: (providerId: string) => typedError<null, AppError>(__TAURI_INVOKE("install_provider", { providerId })),
	listConversations: () => typedError<ConversationMeta[], AppError>(__TAURI_INVOKE("list_conversations")),
	/**
	 *  One session per project for the workspace rail. Unlike `list_conversations` this
	 *  is not scoped to the active project — the sidebar shows every project's sessions.
	 * 
	 *  Turns store the provider *label*, but the icon library keys on the catalogue *id*,
	 *  so a session's `provider` is resolved here where the detection rows are visible.
	 *  Unknown/synthetic labels keep `provider: None` and let the UI fall back to a
	 *  generic chat mark.
	 */
	listWorkspaceSessions: () => typedError<WorkspaceSession[], AppError>(__TAURI_INVOKE("list_workspace_sessions")),
	newConversation: () => typedError<ConversationMeta, AppError>(__TAURI_INVOKE("new_conversation")),
	getConversation: (conversationId: string) => typedError<{
	meta: ConversationMeta,
	turns: ChatTurnView[],
} | null, AppError>(__TAURI_INVOKE("get_conversation", { conversationId })),
	/**
	 *  Removes one conversation and everything in it.
	 * 
	 *  The user's click on the bin **is** the permission for this destructive action, so it
	 *  is not asked for twice — but a turn still streaming is stopped first, or its task
	 *  would go on emitting events for a thread that no longer exists.
	 */
	deleteConversation: (conversationId: string) => typedError<ConversationMeta[], AppError>(__TAURI_INVOKE("delete_conversation", { conversationId })),
	sendChatMessage: (conversationId: string | null, text: string, providerId: string | null, model: string | null, effort: "fast" | "balanced" | "quality" | "ultra" | null, design: 
// Answer normally.
"off" | 
// Hold every interface decision to `docs/DESIGN-SYSTEM.md`.
"on" | null, caveman: boolean | null) => typedError<TurnPair, AppError>(__TAURI_INVOKE("send_chat_message", { conversationId, text, providerId, model, effort, design, caveman })),
	regenerateLastAnswer: (conversationId: string, providerId: string | null, model: string | null, effort: "fast" | "balanced" | "quality" | "ultra" | null, design: 
// Answer normally.
"off" | 
// Hold every interface decision to `docs/DESIGN-SYSTEM.md`.
"on" | null, caveman: boolean | null) => typedError<TurnPair, AppError>(__TAURI_INVOKE("regenerate_last_answer", { conversationId, providerId, model, effort, design, caveman })),
	stopChatTurn: (turnId: string) => typedError<null, AppError>(__TAURI_INVOKE("stop_chat_turn", { turnId })),
	/**
	 *  Put every file one turn changed back as it was (CHT-115).
	 * 
	 *  Returns the number of files restored. The snapshot is session-scoped and consumed, so
	 *  this succeeds once and then reports honestly that there is nothing left to undo — which
	 *  is why the card asks `chat_turn_undoable` before offering the button at all.
	 */
	undoChatTurn: (turnId: string) => typedError<number, AppError>(__TAURI_INVOKE("undo_chat_turn", { turnId })),
	/**
	 *  Whether a turn's changes can still be put back — what disables the Undo button, with a
	 *  reason, instead of letting it fail when pressed.
	 */
	chatTurnUndoable: (turnId: string) => typedError<boolean, AppError>(__TAURI_INVOKE("chat_turn_undoable", { turnId })),
	respondPermission: (requestId: string, allow: boolean) => typedError<null, AppError>(__TAURI_INVOKE("respond_permission", { requestId, allow })),
	getTierBudgets: () => typedError<TierBudgetView[], AppError>(__TAURI_INVOKE("get_tier_budgets")),
	/**
	 *  The usage gauge, its drop-up, and Settings › Usage all read this one summary.
	 * 
	 *  `window` defaults to today; the chart it carries always covers the last 30 days so
	 *  switching windows never re-renders a different-shaped graph.
	 */
	getUsageSummary: (window: "day" | "week" | "month" | 
// The whole retained history (`bhippi_core::RETAINED_DAYS`).
"quarter" | null, refreshAccounts: boolean | null) => typedError<UsageSummary, AppError>(__TAURI_INVOKE("get_usage_summary", { window, refreshAccounts })),
	/**
	 *  The context-telemetry panel: what each turn's prompt carried, by category.
	 * 
	 *  `window` defaults to today; the summary is read straight from the local sample
	 *  log (`~/.bhippi/context.json`) and never includes message or source content.
	 */
	getContextSummary: (window: "day" | "week" | 
// The whole retained history (`bhippi_core::RETAINED_SAMPLES`).
"all" | null) => typedError<ContextSummary, AppError>(__TAURI_INVOKE("get_context_summary", { window })),
	// Clears the whole context-telemetry history.
	clearContextSamples: () => typedError<null, AppError>(__TAURI_INVOKE("clear_context_samples")),
	/**
	 *  Sets one provider's daily token ceiling, or clears it back to the shared default.
	 * 
	 *  `Some(0)` is rejected rather than silently meaning "uncapped" — the caller says what
	 *  it means, and an accidental zero should not quietly switch the gauge off.
	 */
	setProviderTokenCap: (providerId: string, dailyTokens: number | null) => typedError<UsageSummary, AppError>(__TAURI_INVOKE("set_provider_token_cap", { providerId, dailyTokens })),
	/**
	 *  Remembers the model chosen for one provider so the composer restores it next launch.
	 * 
	 *  `None` forgets the choice, which returns that provider to its own default.
	 */
	setProviderModel: (providerId: string, model: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_provider_model", { providerId, model })),
	/**
	 *  Remembers the provider chosen in the composer so it is still chosen next launch.
	 * 
	 *  Only an id the runtime can actually answer with is stored: remembering a backend that
	 *  has since been switched off would restore a dead choice. `None` forgets it.
	 */
	setActiveProvider: (providerId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_active_provider", { providerId })),
	/**
	 *  Clears recorded usage — one provider, or the whole ledger when `provider_id` is None.
	 *  The user's explicit click **is** the permission for this destructive action.
	 */
	clearUsage: (providerId: string | null) => typedError<UsageSummary, AppError>(__TAURI_INVOKE("clear_usage", { providerId })),
	listProjects: () => typedError<ProjectSummary[], AppError>(__TAURI_INVOKE("list_projects")),
	addExistingProject: (path: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("add_existing_project", { path })),
	createProject: (parent: string, name: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("create_project", { parent, name })),
	cloneProject: (gitUrl: string, parent: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("clone_project", { gitUrl, parent })),
	selectProject: (path: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("select_project", { path })),
	forgetProject: (path: string) => typedError<ProjectSummary[], AppError>(__TAURI_INVOKE("forget_project", { path })),
	projectTools: () => typedError<ToolAvailability[], AppError>(__TAURI_INVOKE("project_tools")),
	openProjectIn: (path: string, tool: ProjectTool) => typedError<null, AppError>(__TAURI_INVOKE("open_project_in", { path, tool })),
	initializeProjectGit: (path: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("initialize_project_git", { path })),
	/**
	 *  Lists one directory of the open project, directories first then files, each A–Z.
	 * 
	 *  Listing is per-directory rather than a recursive walk, so opening a large repository
	 *  costs one `read_dir` and a folder nobody expands is never read at all.
	 * 
	 *  # Errors
	 *  Fails when no project is open, when the path leaves the project, or when the
	 *  directory cannot be read.
	 */
	listWorkspaceDir: (relative: string) => typedError<WorkspaceEntry[], AppError>(__TAURI_INVOKE("list_workspace_dir", { relative })),
	/**
	 *  Reads one project file for the editor.
	 * 
	 *  Binary content and anything over 1 MB come back flagged rather than as an error, so
	 *  the editor can say *why* a file will not open instead of showing a blank pane.
	 * 
	 *  # Errors
	 *  Fails when no project is open, when the path leaves the project, or when the file
	 *  cannot be read.
	 */
	readWorkspaceFile: (relative: string) => typedError<WorkspaceFile, AppError>(__TAURI_INVOKE("read_workspace_file", { relative })),
	/**
	 *  Writes a file into the open project, creating it (and parent folders) when missing.
	 * 
	 *  Pressing save **is** the permission for this write, but it is refused for a file
	 *  that was never fully loaded: saving a truncated buffer would silently delete the
	 *  rest of the file.
	 * 
	 *  # Errors
	 *  Fails when no project is open, when the path leaves the project, when the target is
	 *  a directory, or when the write itself fails.
	 */
	writeWorkspaceFile: (relative: string, text: string) => typedError<WorkspaceFile, AppError>(__TAURI_INVOKE("write_workspace_file", { relative, text })),
	/**
	 *  Copies a user-picked file from anywhere on disk into the open project.
	 * 
	 *  Used by Engine Replace Object / texture import. The destination must stay inside
	 *  the project; the source is the path the OS file dialog already authorised.
	 */
	importWorkspaceFile: (sourceAbsolute: string, destRelative: string) => typedError<WorkspaceEntry, AppError>(__TAURI_INVOKE("import_workspace_file", { sourceAbsolute, destRelative })),
	/**
	 *  Probes the usual local dev-server ports and reports what answered.
	 * 
	 *  Nothing here starts a server or assumes a running one: a target is marked reachable
	 *  only when a TCP connection to it succeeded during this call.
	 * 
	 *  # Errors
	 *  Fails when no project is open.
	 */
	previewTargets: () => typedError<PreviewTarget[], AppError>(__TAURI_INVOKE("preview_targets")),
	/**
	 *  Reads the open project's rules file, or reports an empty, not-yet-written one.
	 * 
	 *  A missing file is the ordinary first-run state, not an error — the panel opens on an
	 *  empty editor rather than on a failure the user can do nothing about.
	 * 
	 *  # Errors
	 *  Fails when no project is open, or when an existing rules file cannot be read.
	 */
	readProjectRules: () => typedError<ProjectRules, AppError>(__TAURI_INVOKE("read_project_rules")),
	/**
	 *  Writes the open project's rules file, creating `.bhippi/` on first save.
	 * 
	 *  # Errors
	 *  Fails when no project is open, or when the file cannot be created or written.
	 */
	writeProjectRules: (text: string) => typedError<ProjectRules, AppError>(__TAURI_INVOKE("write_project_rules", { text })),
	// Returns the current Computer Use status, permissions, and provider vision support matrix.
	getComputerUseStatus: () => typedError<ComputerUseStatus, AppError>(__TAURI_INVOKE("get_computer_use_status")),
	// Enables or disables Computer Use in config.
	setComputerUseEnabled: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_computer_use_enabled", { enabled })),
	// Toggles full PC access permission for Computer Use.
	setComputerUseFullAccess: (fullAccess: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_computer_use_full_access", { fullAccess })),
	// Captures a live screen preview for testing vision and resolution.
	captureScreenPreview: () => typedError<ScreenCapture, AppError>(__TAURI_INVOKE("capture_screen_preview")),
	// Executes a Computer Use action (mouse, keyboard, scroll, drag, screenshot).
	executeComputerAction: (action: ComputerAction) => typedError<ComputerActionResult, AppError>(__TAURI_INVOKE("execute_computer_action", { action })),
	// Returns the list of discovered and configured AI skills.
	listSkills: (workspace: string | null) => typedError<Skill[], AppError>(__TAURI_INVOKE("list_skills", { workspace })),
	// Sets the enabled state of a specific skill.
	setSkillEnabled: (skillId: string, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_skill_enabled", { skillId, enabled })),
	// Re-scans and imports skills from pre-installed AI apps (Claude, Codex, Antigravity, Cursor).
	importExternalSkills: (workspace: string | null) => typedError<Skill[], AppError>(__TAURI_INVOKE("import_external_skills", { workspace })),
	// Runs non-AI deterministic diagnostics and typechecking on the active workspace.
	runProjectDiagnostics: (workspace: string | null) => typedError<DiagnosticReport, AppError>(__TAURI_INVOKE("run_project_diagnostics", { workspace })),
	// Clears all turns in the active conversation view.
	cleanConversation: (conversationId: string) => typedError<{
	meta: ConversationMeta,
	turns: ChatTurnView[],
} | null, AppError>(__TAURI_INVOKE("clean_conversation", { conversationId })),
	// Compacts conversation history into a concise summary to preserve token budget.
	compactConversation: (conversationId: string) => typedError<{
	meta: ConversationMeta,
	turns: ChatTurnView[],
} | null, AppError>(__TAURI_INVOKE("compact_conversation", { conversationId })),
	// Queries the git review diff summary for the active project and optional turn.
	getReviewChanges: (workspace: string | null, turnTitle: string | null) => typedError<ReviewSummary, AppError>(__TAURI_INVOKE("get_review_changes", { workspace, turnTitle })),
	runCliCommand: (path: string, shell: string, command: string) => typedError<CliCommandResult, AppError>(__TAURI_INVOKE("run_cli_command", { path, shell, command })),
	// Opens a shell in `path` and starts streaming its output.
	terminalOpen: (path: string, shell: TerminalShell, cols: number, rows: number) => typedError<TerminalSession, AppError>(__TAURI_INVOKE("terminal_open", { path, shell, cols, rows })),
	// Sends keystrokes (or pasted text) to the terminal.
	terminalWrite: (id: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("terminal_write", { id, data })),
	// Tells the PTY its new size, so full-screen programs re-lay-out.
	terminalResize: (id: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("terminal_resize", { id, cols, rows })),
	// Ends a terminal and kills its shell.
	terminalClose: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("terminal_close", { id })),
	openExternalTerminal: (path: string, shell: string, customCmd: string | null) => typedError<null, AppError>(__TAURI_INVOKE("open_external_terminal", { path, shell, customCmd })),
	/**
	 *  Opens an http(s) address in the user's default browser. The in-app browser uses this
	 *  when a site must leave the pane (the dedicated-window buttons on a blocked card).
	 */
	openExternalUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external_url", { url })),
	projectBrainStatus: () => typedError<BrainStatus, AppError>(__TAURI_INVOKE("project_brain_status")),
	rebuildProjectBrain: () => typedError<IndexReport, AppError>(__TAURI_INVOKE("rebuild_project_brain")),
	listProjectModuleCards: () => typedError<ModuleCardView[], AppError>(__TAURI_INVOKE("list_project_module_cards")),
	getProjectModuleCard: (relPath: string) => typedError<{
	module_name: string,
	entry_points: string[],
	public_symbols: string[],
	symbol_count: number,
	description: string | null,
	description_origin: string | null,
	card_revision: number,
	token_estimate: number,
} | null, AppError>(__TAURI_INVOKE("get_project_module_card", { relPath })),
	searchProjectSymbols: (query: string, limit: number | null) => typedError<SymbolHit[], AppError>(__TAURI_INVOKE("search_project_symbols", { query, limit })),
	worldBrainStatus: () => typedError<SceneView[], AppError>(__TAURI_INVOKE("world_brain_status")),
	worldBrainSceneEntities: (sceneId: SceneId) => typedError<SceneEntityView[], AppError>(__TAURI_INVOKE("world_brain_scene_entities", { sceneId })),
	worldBrainFindEntity: (sceneId: SceneId, name: string) => typedError<SceneEntityView[], AppError>(__TAURI_INVOKE("world_brain_find_entity", { sceneId, name })),
	worldBrainIndexScene: (relPath: string, sourceRevision: number) => typedError<SceneView, AppError>(__TAURI_INVOKE("world_brain_index_scene", { relPath, sourceRevision })),
	worldBrainAssets: () => typedError<AssetView[], AppError>(__TAURI_INVOKE("world_brain_assets")),
	worldBrainAssetsByKind: (kind: string) => typedError<AssetView[], AppError>(__TAURI_INVOKE("world_brain_assets_by_kind", { kind })),
	// Scenes that reference an asset — the answer to "what uses this asset?".
	worldBrainAssetUsage: (assetId: AssetId) => typedError<string[], AppError>(__TAURI_INVOKE("world_brain_asset_usage", { assetId })),
	/**
	 *  Re-scan the project's `assets/` tree with the engine's indexer and persist the result
	 *  into the World Brain, replacing the previous asset snapshot. Returns the number of
	 *  assets indexed.
	 */
	worldBrainIndexAssets: (sourceRevision: number) => typedError<number, AppError>(__TAURI_INVOKE("world_brain_index_assets", { sourceRevision })),
	/**
	 *  Every rigid body / collider recorded across the project's scenes — the physics
	 *  graph answer for "which entities are dynamic bodies?", "what colliders exist?".
	 */
	worldBrainPhysics: () => typedError<PhysicsBodyView[], AppError>(__TAURI_INVOKE("world_brain_physics")),
	// The rigid bodies / colliders belonging to one scene.
	worldBrainPhysicsByScene: (sceneId: SceneId) => typedError<PhysicsBodyView[], AppError>(__TAURI_INVOKE("world_brain_physics_by_scene", { sceneId })),
	// The physics record for one entity, if it carries any physics component.
	worldBrainPhysicsByEntity: (entityId: EntityId) => typedError<{
	entity_id: EntityId,
	scene_id: SceneId,
	body_kind: string | null,
	mass: number | null,
	lock_rotation: number | null,
	collider_shape: string | null,
	sensor: number | null,
	has_character_controller: boolean,
	source_revision: number,
} | null, AppError>(__TAURI_INVOKE("world_brain_physics_by_entity", { entityId })),
};

/** Events */
export const events = {
	chatDelta: makeEvent<ChatDelta>("chat-delta"),
	chatLimits: makeEvent<ChatLimits>("chat-limits"),
	chatPermissionRequested: makeEvent<ChatPermissionRequested>("chat-permission-requested"),
	chatThinking: makeEvent<ChatThinking>("chat-thinking"),
	chatThoughtDelta: makeEvent<ChatThoughtDelta>("chat-thought-delta"),
	chatTool: makeEvent<ChatTool>("chat-tool"),
	chatTurnDone: makeEvent<ChatTurnDone>("chat-turn-done"),
	engineGameTestBatchRequested: makeEvent<EngineGameTestBatchRequested>("engine-game-test-batch-requested"),
	enginePlaytestRequested: makeEvent<EnginePlaytestRequested>("engine-playtest-requested"),
	engineSceneChanged: makeEvent<EngineSceneChanged>("engine-scene-changed"),
	engineScreenshotRequested: makeEvent<EngineScreenshotRequested>("engine-screenshot-requested"),
	hudChanged: makeEvent<HudChanged>("hud-changed"),
	providerInstallProgress: makeEvent<ProviderInstallProgress>("provider-install-progress"),
	providersChanged: makeEvent<ProvidersChanged>("providers-changed"),
	terminalExited: makeEvent<TerminalExited>("terminal-exited"),
	terminalOutput: makeEvent<TerminalOutput>("terminal-output"),
};

/* Types */
// Signed-in account identity plus vendor-reported plan usage.
export type AccountUsage = {
	// Email, workspace, or provider-owned account label. Never a credential value.
	account_name: string | null,
	plan: string | null,
	status: AccountUsageStatus,
	session: PlanWindow | null,
	weekly: PlanWindow | null,
	// Plain-language reason for a missing value; the UI never invents one.
	note: string,
	refreshed_at: string,
};

// How much account information a provider made available without reading credentials.
export type AccountUsageStatus = 
// Identity and rolling windows came from a vendor-owned status protocol.
"live" | 
// The provider confirmed the account, but exposes no numerical plan allowance.
"authenticated" | 
// The CLI is present but the provider does not expose this information.
"not_reported" | 
// The provider explicitly reported that no account is signed in.
"signed_out" | 
// A supported account probe failed; the previous good snapshot may still be shown.
"unavailable";

export type ActionBinding = {
	name: string,
	keys: string[],
};

/**
 *  What the agent is doing right now, in a vocabulary the UI can animate.
 * 
 *  The engine used to emit one free-text label ("Connecting to Claude Code"), which the
 *  UI could only print. A closed set means each state gets its own motion, its own icon,
 *  and its own copy — and means adding a state is a compile error everywhere it has to
 *  be handled rather than a string that silently renders as nothing.
 */
export type AgentPhase = 
// Starting the backend process.
"connecting" | 
// Waiting behind another turn.
"queued" | 
// The model is deliberating before it says anything.
"thinking" | 
// Extended reasoning, streamed as it happens.
"reasoning" | 
// Laying out the steps it intends to take.
"planning" | 
// Searching the workspace or the web.
"searching" | 
// Reading a file.
"reading" | 
// Writing a new file.
"writing" | 
// Changing an existing file.
"editing" | 
// Restructuring code it already changed.
"refactoring" | 
// Running a command.
"running" | 
// Running tests.
"testing" | 
// Compiling.
"building" | 
// Working out why something failed.
"debugging" | 
// Installing or updating a dependency.
"installing" | 
// Fetching a URL.
"fetching" | 
// Driving a browser or the desktop.
"browsing" | 
// Working over what it gathered.
"analyzing" | 
// Condensing what it found.
"summarizing" | 
// Checking its own work.
"reviewing" | 
// Blocked on the user's answer.
"awaiting_permission" | 
// Condensing the conversation to fit the context window.
"compacting" | 
// Trying again after a recoverable failure.
"retrying" | 
// Producing the answer text.
"streaming" | 
// Wrapping up.
"finalizing" | 
// Finished cleanly.
"done" | 
// Stopped by the user.
"stopped" | 
// Ended on a fault.
"failed";

// Serializable error crossing IPC; carries the actionable hint where one exists (R1).
export type AppError = {
	message: string,
	hint: string | null,
};

export type AppStatus = {
	version: string,
	// Label of the default answerer right now.
	active_provider: string,
	active_provider_id: string,
	// True when the default answerer is the labelled offline demo (ADR-0006 §4).
	demo_mode: boolean,
	// Every detection row, enabled or not — Settings › Providers renders these.
	providers: ProviderInfo[],
	// Rows the chat picker may show: enabled **and** usable (ADR-0006).
	chat_options: ProviderInfo[],
	tokens_today: number,
	queue_depth: number,
	/**
	 *  The model the user last picked per provider, so the composer opens where they left
	 *  it rather than resetting to a default they did not choose.
	 */
	last_model: { [key in string]: string },
	/**
	 *  The provider the user last picked, when it is still enabled and reachable. `None`
	 *  leaves the composer on `active_provider_id` — a backend that has gone away is
	 *  never silently swapped for another one.
	 */
	last_provider: string | null,
};

export type AssetId = string;

/**
 *  What an imported asset is, used by the drawer's type badges and the schema's
 *  `asset:<kind>` field level.
 */
export type AssetKind = "mesh" | "skeleton" | "texture" | "material" | "audio" | "animation" | "scene" | "script" | "prefab" | "ui" | "font" | "shader" | "other";

// One record of the asset index (ULID ⇄ relative path ⇄ blake3 hash).
export type AssetRecord = {
	id: AssetId,
	path_rel: string,
	kind: AssetKind,
	hash: string,
	license: LicenseState,
	size_bytes: number,
	/**
	 *  Scenes that reference the asset (from the scene documents). Cross-referencing lets
	 *  "find things to edit" become a lookup instead of a search.
	 */
	used_by_scenes?: SceneId[],
};

/**
 *  A persisted asset row as shipped to the UI: stable ULID id, path, kind and licence,
 *  without the raw JSON reverse-usage payload (fetched per-asset on demand).
 */
export type AssetView = {
	asset_id: AssetId,
	rel_path: string,
	kind: string,
	license: string,
	size_bytes: number,
	source_revision: number,
};

export type AxisBinding = {
	name: string,
	positive: string[],
	negative: string[],
};

export type BrainStatus = {
	indexed: boolean,
	revision: number,
	symbol_count: number,
	module_names: string[],
	embedding_model: string | null,
	index_version: string,
};

export type CategoryCount = {
	category: string,
	count: number,
};

export type ChatDelta = {
	turn_id: string,
	delta: string,
};

export type ChatLimits = {
	provider: string,
	limits: LimitSnapshot,
};

export type ChatPermissionRequested = {
	turn_id: string,
	request: PermissionRequest,
};

export type ChatRole = "user" | "assistant";

export type ChatThinking = {
	turn_id: string,
	label: string,
	// The typed state behind the label, so the UI animates rather than just prints.
	phase: AgentPhase,
};

export type ChatThoughtDelta = {
	turn_id: string,
	delta: string,
};

export type ChatTool = {
	turn_id: string,
	tool: ToolActivity,
};

export type ChatTurnDone = {
	turn_id: string,
	state: TurnState,
	usage: Usage | null,
	error: string | null,
	fault: TurnFault | null,
};

// One message in a conversation, as the UI renders it.
export type ChatTurnView = {
	id: string,
	conversation_id: string,
	role: ChatRole,
	content: string,
	// Chain-of-thought internal reasoning trace (e.g. from reasoning models or <think> blocks).
	thinking?: string | null,
	// Milliseconds spent thinking before beginning the actual response stream.
	thinking_elapsed_ms?: number | null,
	created_at: string,
	state: TurnState,
	// Which backend produced this turn (`demo` renders the offline badge).
	provider: string | null,
	tools: ToolActivity[],
	permission: PermissionRequest | null,
	/**
	 *  Why this turn failed, when it did — reloaded with the conversation so a fault
	 *  card survives a restart instead of vanishing into an unexplained empty turn.
	 */
	fault?: TurnFault | null,
	/**
	 *  Wall-clock milliseconds from the turn starting to it finishing (CHT-103). Computed
	 *  here rather than in the pane: a duration derived from two timestamps in TypeScript is
	 *  a duration that drifts with the clock the browser happens to be reading (INV-051).
	 */
	worked_ms?: number | null,
	// What this turn changed on disk, folded across its steps (CHT-104).
	changes?: TurnChanges | null,
	// Usage limits, rate limits and provider warnings (CHT-106).
	notices?: TurnNotice[],
};

export type CliCommandResult = {
	stdout: string,
	stderr: string,
	exit_code: number | null,
	success: boolean,
};

export type ComputerAction = { type: "screenshot" } | { type: "mouse_move"; x: number; y: number } | { type: "mouse_click"; button: string; count: number; x: number | null; y: number | null } | { type: "mouse_drag"; start_x: number; start_y: number; end_x: number; end_y: number } | { type: "mouse_scroll"; delta_x: number; delta_y: number } | { type: "type_text"; text: string } | { type: "key_press"; key: string } | { type: "hotkey"; keys: string[] } | { type: "get_screen_size" } | { type: "get_cursor_position" };

export type ComputerActionResult = {
	success: boolean,
	action: string,
	detail: string,
	screenshot: ScreenCapture | null,
	cursor: [number, number] | null,
	screen_size: [number, number] | null,
	screen_origin: [number, number] | null,
};

export type ComputerUseStatus = {
	enabled: boolean,
	full_access: boolean,
	allowed_providers: string[],
	supported_providers: ProviderVisionCapability[],
};

// One category's weight inside the window.
export type ContextCategoryView = {
	// `ContextCategory::as_str()`.
	category: string,
	samples: number,
	// Mean estimated tokens per sample for this category.
	avg_tokens: number,
	// `0.0..=1.0` of the window's total attributed to this category.
	share: number,
};

// One day's samples, for the trend chart.
export type ContextDayPoint = {
	// `YYYY-MM-DD` (UTC).
	date: string,
	samples: number,
	avg_input: number,
};

// One provider's weight inside the window.
export type ContextProviderView = {
	provider_id: string,
	samples: number,
	avg_input: number,
	avg_output: number,
};

// Everything the context panel needs in one read.
export type ContextSummary = {
	window: ContextWindow,
	window_label: string,
	samples: number,
	// Turns whose assembled prompt already filled the provider's window.
	turns_with_over_window: number,
	// Turns that carried a multi-provider handoff note.
	handoff_turns: number,
	mean_total_input: number,
	median_total_input: number,
	max_total_input: number,
	// Mean answer budget reserved per sample (`max_tokens`), not the actual answer.
	mean_output_estimate: number,
	// Heaviest category first.
	categories: ContextCategoryView[],
	// Every provider with samples in the window, heaviest first.
	providers: ContextProviderView[],
	// Oldest to newest, one row per day that has samples.
	by_day: ContextDayPoint[],
};

// How much history one summary covers. `Day` is the default the chart opens on.
export type ContextWindow = "day" | "week" | 
// The whole retained history (`bhippi_core::RETAINED_SAMPLES`).
"all";

export type ConversationMeta = {
	id: string,
	project_path: string,
	title: string,
	created_at: string,
	turn_count: number,
};

export type ConversationView = {
	meta: ConversationMeta,
	turns: ChatTurnView[],
};

// One provider's slice of one day, for the chart's per-provider series.
export type DayProviderPoint = {
	id: string,
	total_tokens: number,
	cost_usd: number,
};

/**
 *  Whether this turn must follow the Bhippi Design System.
 * 
 *  A flag rather than a persistent setting, and on the turn rather than in config, for the
 *  same reason `Effort` is: it changes what one answer should be, and the user decides that
 *  per question. Someone asking "why is this failing" does not want a design brief in the
 *  reply; someone asking for a settings page does.
 */
export type DesignMode = 
// Answer normally.
"off" | 
// Hold every interface decision to `docs/DESIGN-SYSTEM.md`.
"on";

export type DiagnosticItem = {
	file: string,
	line: number | null,
	column: number | null,
	severity: string,
	category: string,
	// The rule id (`BHP-D001`) or the tool that reported it (`rustc`, `tsc`).
	code: string | null,
	message: string,
	// Why this is a defect rather than a preference.
	why: string,
	suggestion: string | null,
	// The offending source, trimmed.
	evidence: string,
};

// A finished scan, as the UI renders it.
export type DiagnosticReport = {
	project_name: string,
	// Every stack found, joined — a repository is frequently more than one thing.
	project_type: string,
	total_issues: number,
	errors_count: number,
	warnings_count: number,
	info_count: number,
	duration_ms: number,
	// How many files were actually read.
	files_scanned: number,
	/**
	 *  How much source those files held. A file count alone hides whether a scan
	 *  covered a real project or a directory of stubs.
	 */
	bytes_scanned: number,
	/**
	 *  True when a budget stopped the scan early. A partial scan is not a clean one, and
	 *  the UI must say so rather than reporting a pass.
	 */
	partial: boolean,
	items: DiagnosticItem[],
	/**
	 *  One line per toolchain that ran, so a tool that could not start is visible rather
	 *  than silently contributing nothing.
	 */
	tools: ToolStatus[],
	// Counts per category, for the report header.
	by_category: CategoryCount[],
	summary: string,
	success: boolean,
};

export type DiffHunk = {
	old_start: number,
	old_lines: number,
	new_start: number,
	new_lines: number,
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	line_type: DiffLineType,
	old_line_num: number | null,
	new_line_num: number | null,
	content: string,
};

export type DiffLineType = "added" | "deleted" | "context";

/**
 *  Response effort, shown as the composer's speed control (Faster ↔ Smarter).
 * 
 *  Every level changes three real knobs — token ceiling, temperature, and one system
 *  directive — so the choice is visible in the answer, not decorative.
 */
export type Effort = "fast" | "balanced" | "quality" | "ultra";

/**
 *  The per-action result envelope (ENG-112).
 * 
 *  A model that gets back only "failed" learns nothing. This carries the index that broke,
 *  the engine's own message and hint, and — when the action named a component — the schema
 *  excerpt for it, so the repair round has the real field list instead of a guess.
 */
export type EngineActionOutcome = {
	index: number,
	ok: boolean,
	// The action's own one-line label ("spawn cube"), or its `kind` when it never parsed.
	label: string,
	message: string,
	hint: string | null,
	schema_excerpt: string | null,
};

// Every asset in the project, for the Content Browser and the asset pickers (ENG-143).
export type EngineAssetView = {
	id: string,
	path: string,
	name: string,
	kind: string,
	license: string,
	size_bytes: number,
};

/**
 *  What a batch did. `applied` is false when nothing was written — a batch is all-or-
 *  nothing, because a half-built level is worse than none.
 */
export type EngineBatchResult = {
	applied: boolean,
	label: string,
	scene_path: string,
	outcomes: EngineActionOutcome[],
	// Present when the batch applied.
	edit: EngineEditResult | null,
	// The scene state either way, so a caller that failed still renders current truth.
	state: EngineSceneState,
};

// One row of the Agent permissions panel.
export type EngineCapabilityRow = {
	capability: string,
	decision: string,
	doc: string,
	// Whether this is still the shipped default, so the panel can say what was changed.
	is_default: boolean,
};

// One entity's compiled gameplay script.
export type EngineCompiledScript = {
	entity: string,
	path: string,
	program: ScriptProgram,
};

// One component and its fields.
export type EngineComponentView = {
	name: string,
	doc: string,
	/**
	 *  The Details panel groups by this: Transform, Rendering, Physics, Audio, Gameplay,
	 *  Scripting, Editor.
	 */
	category: string,
	fields: EngineFieldView[],
};

export type EngineConsoleRow = {
	id: number,
	at: string,
	level: string,
	channel: string,
	text: string,
	file: string | null,
	line: number | null,
};

/**
 *  What one applied transaction did — returned to the caller and broadcast as an event so
 *  panels patch the touched entities instead of reloading the scene (ENG-107, INV-076).
 */
export type EngineEditResult = {
	scene_path: string,
	txn_id: string,
	// `user` | `agent`
	actor: string,
	label: string,
	summary: string,
	op_count: number,
	touched: EntityId[],
	state: EngineSceneState,
	/**
	 *  Set when the transaction was journaled; `None` means the journal was unavailable
	 *  (the edit still applied — the ledger is a record, not a gate).
	 */
	revision: number | null,
};

// One editable field of a component, as the Details panel renders it (ENG-142).
export type EngineFieldView = {
	name: string,
	// `f32` · `vec3` · `vec4` · `i32` · `bool` · `enum` · `string` · `asset` · `color` · `json`
	kind: string,
	doc: string,
	min: number | null,
	max: number | null,
	// Present for `enum`.
	options: string[],
	// Present for `asset` — which kind of asset the picker should offer.
	asset_kind: string | null,
	// Registry-owned value written by Reset.
	default_value: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
};

/**
 *  A validated authored scenario plan ready for execution in fresh disposable workers.
 * 
 *  The plan crosses IPC as canonical JSON so the webview cannot reinterpret an invalid Rust
 *  document. The authored hash is retained in the pending request and must match the submitted
 *  batch evidence byte-for-byte.
 */
export type EngineGameTestBatchRequested = {
	request_id: string,
	plan_json: string,
	authored_tree_hash: string,
	fixed_delta_seconds: number,
	/**
	 *  Rust-owned ceiling for the whole batch request; every scenario still runs in its own
	 *  disposable worker and reports its own sandbox budgets.
	 */
	watchdog_millis: number,
};

// The project-root-relative location a game was (or would be) scaffolded at.
export type EngineGameView = {
	name: string,
	version: string,
	default_scene: string,
	engine_track: string,
	targets: string[],
	scene_exists: boolean,
	hud_scene: string | null,
	levels: string[],
	scenes: string[],
};

// One row of the transaction journal, as the Engine pane's history list renders it.
export type EngineHistoryEntry = {
	revision: number,
	txn_id: string,
	// `user` | `agent`
	actor: string,
	issued_at: string,
	label: string,
	scene_path: string,
	op_count: number,
	touched: EntityId[],
};

export type EnginePlayStats = {
	fps: number,
	frame_ms: number,
	entities: number,
	simulated_bodies: number,
	contacts: number,
	draw_calls: number,
	scripts: number,
	script_faults: number,
	elapsed: number,
	paused: boolean,
};

// The world Play runs: Main + one level + the HUD, composed in Rust (ENG-105 / ENG-170).
export type EnginePlayWorld = {
	scene_path: string,
	level_path: string | null,
	hud_path: string | null,
	// The composed `bhippi-scene@1` world, ready to render.
	document_json: string,
	/**
	 *  The `bhippi-hud@1` overlay drawn on top, when the game has one. Separate from the
	 *  world because the HUD is 2D and edited as a HUD, not merged in as 3D entities.
	 */
	hud_json: string | null,
	// Widgets pre-resolved to canvas pixels, so the overlay renderer places nothing itself.
	hud_widgets: HudWidgetView[],
	// The reference resolution the widget rects are expressed in.
	hud_reference: [number, number],
	// Runtime gravity comes from the manifest, never from renderer constants.
	gravity: [number, number, number],
	// Validated, hand-editable named input actions and axes.
	input: InputDocument,
	// Ordered level paths available to runtime level travel.
	levels: string[],
	/**
	 *  Gameplay scripts compiled for this world (ADR-0030): one entry per entity whose
	 *  `ScriptRef` resolved and compiled. The webview VM executes these; it never parses.
	 */
	scripts: EngineCompiledScript[],
	/**
	 *  Exact broker grants derived in Rust from the compiled programs. The webview may lower
	 *  these grants but cannot invent another worker capability.
	 */
	runtime_capabilities: RuntimeCapability[],
	// Application-owned ceilings for this disposable run.
	runtime_budgets: RuntimeBudgets,
	/**
	 *  Scripts that would not compile. Play still starts — those entities simply run
	 *  unscripted — and the fault lands in the Output Log with its file and line, because a
	 *  game that refuses to start over one prop's typo is worse than a located error.
	 */
	script_faults: ScriptFault[],
};

export type EnginePlaytestRequested = {
	request_id: string,
	steps_json: string,
	fixed_delta_seconds: number,
	// Rust-owned ceiling for the worker request; the outer one-shot uses the same bound.
	watchdog_millis: number,
};

export type EngineQueryAnimationGraphView = {
	entity: EntityId,
	clip: AssetId | null,
	clip_record: AssetRecord | null,
	mesh: AssetId | null,
	co_referenced: AssetId[],
};

export type EngineQueryAssetDependenciesView = {
	asset: AssetId,
	record: AssetRecord | null,
	dependencies: EngineQueryAssetDependency[],
};

export type EngineQueryAssetDependency = {
	asset: AssetId,
	record: AssetRecord | null,
};

export type EngineQueryAssetUser = {
	entity: EntityId,
	name: string,
	stable_path: string,
	components: string[],
	payloads: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
};

export type EngineQueryAssetUsersView = {
	asset: AssetId,
	record: AssetRecord | null,
	users: EngineQueryAssetUser[],
};

export type EngineQueryChildrenView = {
	entity: EntityId,
	ids: EntityId[],
	entries: EngineQueryEntityRef[] | null,
};

export type EngineQueryComponentsView = {
	entity: EntityId,
	names: string[],
	payloads: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
};

export type EngineQueryEntityRef = {
	id: EntityId,
	name: string,
	parent: EntityId | null,
	stable_path: string,
};

export type EngineQueryEntityView = {
	id: EntityId,
	name: string,
	parent: EntityId | null,
	tags: string[],
	stable_path: string,
	component_names: string[],
	components: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
};

export type EngineQueryMaterialGraphView = {
	material: AssetId,
	record: AssetRecord | null,
	users: EngineQueryAssetUser[],
	textures: AssetId[],
};

export type EngineQueryParentView = {
	entity: EntityId,
	parent: EngineQueryEntityRef | null,
	parent_components: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
};

export type EngineQueryPhysicsView = {
	entity: EntityId,
	body_kind: string | null,
	mass: number | null,
	lock_rotation: boolean | null,
	collider_shape: string | null,
	sensor: boolean | null,
	has_character_controller: boolean,
	extras: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } } | null,
};

export type EngineQuerySceneView = {
	id: SceneId,
	name: string,
	kind: SceneKind,
	entity_count: number,
	root_count: number,
	settings: SceneSettings | null,
	hierarchy: HierarchyEntry[] | null,
};

export type EngineQueryScriptsView = {
	entity: EntityId,
	script: string | null,
	hooks: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
	config: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
};

export type EngineQueryShaderView = {
	shader: AssetId,
	record: AssetRecord | null,
	users: EngineQueryAssetUser[],
};

/**
 *  One applied transaction, broadcast so panels patch what changed instead of reloading
 *  the scene (ENG-107). `touched` is the entity list the viewport re-reads; everything
 *  else is what the toast and the history row render.
 */
export type EngineSceneChanged = {
	scene_path: string,
	summary: string,
	txn_id: string,
	// `user` | `agent`
	actor: string,
	label: string,
	touched: EntityId[],
	entity_count: number,
	dirty: boolean,
	revision: number,
};

export type EngineSceneDiff = {
	scene_path: string,
	mine_json: string,
	disk_json: string,
};

// Structured scene snapshot the AI and the editor share (engine plan §76–78).
export type EngineSceneQuery = {
	scene_path: string,
	name: string,
	entity_count: number,
	digest: string,
	hierarchy: HierarchyEntry[],
};

/**
 *  The scene state the webview renders. Everything here is derived — the webview owns no
 *  scene state of its own and never writes a scene file.
 */
export type EngineSceneState = {
	scene_path: string,
	name: string,
	kind: SceneKind,
	settings: SceneSettings,
	entity_count: number,
	dirty: boolean,
	can_undo: boolean,
	can_redo: boolean,
	undo_label: string | null,
	redo_label: string | null,
	revision: number,
	selection: EntityId[],
	disk_conflict: boolean,
	// A crash-safe snapshot exists under `.bhippi/engine/autosave/` and can be replayed.
	recovery_available: boolean,
	document_json: string,
};

export type EngineScreenshotRequested = {
	request_id: string,
	camera: string,
	annotate: boolean,
};

// The engine bound for the active project: whether it has a playable game, and where.
export type EngineStatus = {
	game_root: string | null,
	game: EngineGameView | null,
};

/**
 *  The spawn palette, straight from the engine scaffold — the Add menu renders this
 *  instead of building entities in TypeScript (ENG-105, INV-073).
 */
export type EngineTemplateView = {
	name: string,
	label: string,
	kind: string,
};

export type EntityId = string;

/**
 *  A deterministic filter for [`SceneQueries::find_entities`]. `None` fields are not
 *  tested; when every provided field must match. `roots_only` restricts to root entities.
 */
export type EntityQuery = {
	name?: string | null,
	tag?: string | null,
	has_component?: string | null,
	parent?: EntityId | null,
	roots_only?: boolean,
};

export type FileDiff = {
	path: string,
	filename: string,
	directory: string,
	additions: number,
	deletions: number,
	status: string,
	hunks: DiffHunk[],
};

// One thing wrong with the project's content.
export type GateFinding = {
	level: GateLevel,
	// Stable slug so the UI and tests can key on it: `missing_level`, `dangling_asset`, …
	code: string,
	message: string,
	hint: string,
	// Where it was found — a scene path, an asset path, or the manifest.
	where_: string,
};

// How bad one finding is.
export type GateLevel = 
// The project is broken in a way that will surface later. Blocks.
"blocker" | 
// Worth fixing; does not block.
"warning";

// The result of a content check.
export type GateReport = {
	findings: GateFinding[],
};

export type Health = { status: "healthy"; latency_ms: number } | { status: "degraded"; reason: string } | { status: "unavailable"; reason: string } | { status: "disabled" };

/**
 *  A flattened, parent-before-child projection of the hierarchy — the exact tree shape
 *  the Hierarchy panel renders and the AI addresses entities through.
 */
export type HierarchyEntry = {
	id: EntityId,
	name: string,
	parent: EntityId | null,
	children: EntityId[],
	component_names: string[],
	// Transform position for the lineage chips; `None` when absent (never in valid scenes).
	pos: [number, number, number] | null,
};

// One HUD edit, broadcast so a second pane (or the chat dock) sees it land.
export type HudChanged = {
	path: string,
	label: string,
	revision: number,
	dirty: boolean,
};

export type HudPropView = {
	name: string,
	// `text` · `number` · `bool` · `asset` · `enum`
	kind: string,
	// Present for `enum`.
	options: string[],
	doc: string,
};

// The state the HUD editor renders.
export type HudState = {
	path: string,
	name: string,
	reference: [number, number],
	scale_mode: string,
	safe_area: number,
	dirty: boolean,
	can_undo: boolean,
	can_redo: boolean,
	undo_label: string | null,
	revision: number,
	selection: string | null,
	// Widgets in draw order, parents before children.
	widgets: HudWidgetView[],
	// The canonical `bhippi-hud@1` document, for the Details panel to read fields from.
	document_json: string,
};

// One widget kind offered by the Add menu, with the fields the Details panel renders.
export type HudWidgetKindView = {
	kind: string,
	label: string,
	is_container: boolean,
	props: HudPropView[],
};

/**
 *  One widget as the editor renders it: identity, tree position, and the rectangle already
 *  resolved into canvas pixels so the webview does no anchor maths (INV-073).
 */
export type HudWidgetView = {
	id: string,
	name: string,
	kind: string,
	parent: string | null,
	order: number,
	visible: boolean,
	locked: boolean,
	is_container: boolean,
	// `[x, y, width, height]` in reference-resolution pixels, origin top-left.
	rect: [number, number, number, number],
	// Depth in the widget tree, so the Outliner can indent without walking it.
	depth: number,
};

// View of a [`bhippi_memory::IndexResult`] crossing IPC (plain numeric fields).
export type IndexReport = {
	files_scanned: number,
	files_changed: number,
	files_removed: number,
	symbols_counted: number,
	revision: number,
};

export type InputDocument = {
	format: string,
	actions?: ActionBinding[],
	axes?: AxisBinding[],
};

/**
 *  One instruction. Flat and fixed-width so the wire form is an array of small objects
 *  rather than a tagged union the webview would have to narrow.
 */
export type Instr = {
	op: OpCode,
	a: number,
	b: number,
	// Source line, so a runtime fault is located without a side table.
	line: number,
};

/**
 *  Licence state of an imported asset (plan §11.2). `Unknown` blocks Release builds,
 *  Debug builds warn-list (INV-074).
 */
export type LicenseState = "Unknown" | string;

// Where the account stands against a backend's rolling plan windows.
export type LimitSnapshot = {
	// `allowed`, `allowed_warning`, or `rejected`.
	status: string,
	session_used: number | null,
	session_resets_at: number | null,
	weekly_used: number | null,
	weekly_resets_at: number | null,
};

// One model's spend inside the requested window for one provider.
export type ModelUsage = {
	id: string,
	label: string,
	input_tokens: number,
	output_tokens: number,
	total_tokens: number,
	turns: number,
	cost_usd: number,
	/**
	 *  True when `cost_usd` came from this model's own published rate rather than from
	 *  the vendor's default-model price. The panel labels an inexact figure.
	 */
	cost_is_exact: boolean,
};

/**
 *  A module knowledge card as shipped to the UI (PublicModuleCard conflicts with
 *  the app's own conceptual naming, so this stays literal: ModuleCardView).
 */
export type ModuleCardView = {
	module_name: string,
	entry_points: string[],
	public_symbols: string[],
	symbol_count: number,
	description: string | null,
	description_origin: string | null,
	card_revision: number,
	token_estimate: number,
};

export type NoticeLevel = "info" | "warn" | "error";

// The VM's instruction set. Serialised `snake_case`, matched one-for-one in `scriptVm.ts`.
export type OpCode = 
// `a` indexes `numbers`.
"push_num" | 
// `a` indexes `strings`.
"push_str" | 
// `a` is 0 or 1.
"push_bool" | "push_unit" | 
// `a` is a local slot.
"load" | 
// `a` is a local slot; the value is popped.
"store" | "pop" | "add" | "sub" | "mul" | "div" | "rem" | "neg" | "not" | "eq" | "ne" | "lt" | "le" | "gt" | "ge" | 
// `a` is a code index.
"jump" | 
// Pops; `a` is a code index.
"jump_if_false" | 
// Peeks (leaves the value) and jumps when falsy — `&&` short-circuit.
"jump_if_false_peek" | 
// Peeks and jumps when truthy — `||` short-circuit.
"jump_if_true_peek" | 
// `a` indexes the program's own `hosts` list, `b` is the argument count.
"call_host" | 
// `a` indexes `functions`, `b` is the argument count.
"call_user" | "return";

// A consequential action waiting for an explicit human answer (ADR-0006 §3).
export type PermissionRequest = {
	id: string,
	action: string,
	scope: string,
	detail: string,
	risk: RiskLevel,
};

/**
 *  A persisted World Brain physics body/collider (SEC 7.3, ADR-0026). `body_kind` is
 *  one of static/dynamic/kinematic (or null for a collider-only entity); `collider_shape`
 *  is the authored shape descriptor. `mass` is in kg for dynamic bodies.
 */
export type PhysicsBodyView = {
	entity_id: EntityId,
	scene_id: SceneId,
	body_kind: string | null,
	mass: number | null,
	lock_rotation: number | null,
	collider_shape: string | null,
	sensor: number | null,
	has_character_controller: boolean,
	source_revision: number,
};

// One vendor-owned rolling allowance window.
export type PlanWindow = {
	// Fraction consumed, in the closed range `0.0..=1.0`.
	used_fraction: number,
	// Unix seconds for the next reset when the vendor reports it.
	resets_at: number | null,
	// Window length from the vendor, used to distinguish short and weekly buckets.
	duration_minutes: number | null,
};

// The one primary button on a card. Also derived.
export type PluginAction = "open" | "install" | "update" | "configure";

// One row of the merged view the Plugins screen renders.
export type PluginMetadata = {
	id: string,
	name: string,
	version: string,
	description: string,
	category: string,
	// A glyph key the screen maps to an icon. An unknown key falls back to a generic one.
	icon: string,
	status: PluginStatus,
	action: PluginAction,
	// The enable toggle. Built-ins toggle too — they just cannot be uninstalled.
	activated: boolean,
	installed: boolean,
	built_in: boolean,
	/**
	 *  `screen:research`, `workbench:browser`, `panel:brain`, `settings:Usage` … The
	 *  screen maps this to a route; anything it does not recognise opens nothing.
	 */
	target: string | null,
	// The Settings tab this plugin is configured from, when it has one.
	settings_tab: string | null,
	// Unix seconds; 0 for a catalogue entry the user never installed. Drives "Recent".
	installed_at: number,
	window: PluginWindow | null,
};

/**
 *  What the card's badge says. Derived, never stored — a stored badge goes stale the
 *  moment the catalogue moves.
 */
export type PluginStatus = 
// Ships inside the binary. Can be switched off, never removed.
"built_in" | 
// Present and usable.
"installed" | 
// Installed, but the catalogue carries a newer version than the record.
"update_available" | 
// The capability exists but is unusable until its Settings tab is filled in.
"needs_setup" | 
// Shipped early and honestly labelled: not finished yet.
"beta" | 
// In the catalogue, not installed.
"available";

// A window a URL-installed plugin asks for.
export type PluginWindow = {
	title: string,
	width: number,
	height: number,
	url: string,
};

// A localhost address the in-app browser can try.
export type PreviewTarget = {
	url: string,
	/**
	 *  Where the guess came from — a framework default, plus the project's own dev
	 *  script when it has one. Never an invented address.
	 */
	label: string,
	// True only when a TCP connection to that port actually succeeded just now.
	reachable: boolean,
};

// Rules the project owner wrote, plus where they are stored.
export type ProjectRules = {
	// Markdown as typed. Empty when the file does not exist yet.
	text: string,
	// Project-relative location, shown so the file can be edited outside Bhippi too.
	path: string,
	// False before the file has ever been saved.
	exists: boolean,
};

export type ProjectSummary = {
	name: string,
	path: string,
	is_git_repository: boolean,
	branch: string | null,
	active: boolean,
	last_opened_at: number,
};

export type ProjectTool = "vs_code" | "cursor" | "antigravity" | "explorer";

// A detected provider row for Settings › Providers (subset until S1 probing lands).
export type ProviderInfo = {
	id: string,
	label: string,
	kind: ProviderKind,
	models: string[],
	health: Health,
	// True when detection found only the credential, not a reachable backend.
	offered: boolean,
	detected_at: string,
	// CLI on PATH · server reachable · credential present · demo always.
	installed: boolean,
	// CLI `--version` output, trimmed. Servers/clouds report no version yet.
	version: string | null,
	// User preference — only enabled providers appear in the chat picker.
	enabled: boolean,
	/**
	 *  True when the backend pins a model with its own flag yet names no known list —
	 *  the composer then offers a free-text field rather than guessing vendor ids.
	 */
	accepts_custom_model: boolean,
	// The active TCP port discovered during server detection.
	detected_port?: number | null,
};

export type ProviderInstallProgress = {
	id: string,
	phase: string,
	message: string,
};

export type ProviderKind = "cli" | "cloud_api" | "local_server" | "demo";

// One provider's spend inside the requested window.
export type ProviderUsage = {
	id: string,
	label: string,
	kind: ProviderKind,
	input_tokens: number,
	output_tokens: number,
	total_tokens: number,
	turns: number,
	// Estimated list-price spend in USD. Always `0.0` when `metered` is false.
	cost_usd: number,
	// True when this vendor bills per token, so the dollar figure carries meaning.
	metered: boolean,
	/**
	 *  True when every token in this row was priced at its own model's published rate.
	 *  False means part of the spend fell back to the vendor default and the dollar
	 *  figure is an estimate — which the panel must say out loud.
	 */
	cost_is_exact: boolean,
	/**
	 *  The ceiling for this window, or `None` when the provider is uncapped — the ring
	 *  then renders as an empty track rather than as instantly full.
	 */
	limit_tokens: number | null,
	// `0.0..=1.0` of `limit_tokens` already spent. `0.0` when uncapped.
	fraction: number,
	// True when the provider is enabled and reachable right now.
	available: boolean,
	// `0.0..=1.0` of the window's tokens that ran through this provider.
	share_of_tokens: number,
	/**
	 *  `0.0..=1.0` of the window's estimated cost. Always `0.0` for an unmetered
	 *  backend, which spends tokens but no money.
	 */
	share_of_cost: number,
	/**
	 *  Fixed slot in the chart's categorical palette, by catalogue position — so a
	 *  provider keeps its colour when another one drops out of the window (ADR-0011).
	 */
	color_slot: number,
	/**
	 *  Current account balance in USD. This is populated from the balance field
	 *  in the usage ledger when available.
	 */
	balance_usd: number | null,
	/**
	 *  Signed-in identity and real provider plan windows. A missing weekly value is never
	 *  replaced with Bhippi's local cap.
	 */
	account: AccountUsage | null,
	// Per-model breakdown for this provider in the window.
	models: ModelUsage[],
};

export type ProviderVisionCapability = {
	id: string,
	label: string,
	vision_supported: boolean,
	computer_use_allowed: boolean,
	note: string,
};

export type ProvidersChanged = {
	providers: ProviderInfo[],
};

// Everything the viewport needs to draw the open scene truthfully.
export type RenderManifest = {
	scene_path: string,
	materials: RenderMaterial[],
	meshes: RenderMesh[],
	/**
	 *  References the scene points at that do not resolve — the viewport draws a marked
	 *  placeholder for these rather than a plausible grey box that hides the problem.
	 */
	missing: string[],
};

/**
 *  One fully-resolved material, ready for the renderer to build (ENG-162).
 * 
 *  Everything a draw call needs, already looked up: the `.mat.json` parsed, `asset:` texture
 *  references resolved to files on disk, defaults filled in. The webview builds a material
 *  from this and makes no decisions — which is what stops "what the AI generated" and "what
 *  the user sees" from being two different things (F8).
 */
export type RenderMaterial = {
	// The reference entities point at (a `.mat.json` path, or `asset:<ulid>`).
	key: string,
	name: string,
	base_color: [number, number, number],
	roughness: number,
	metallic: number,
	emissive: [number, number, number],
	emissive_strength: number,
	normal_strength: number,
	tiling: [number, number],
	offset: [number, number],
	// `opaque` · `mask` · `blend`
	alpha_mode: string,
	alpha_cutoff: number,
	double_sided: boolean,
	// Absolute paths, for the webview to turn into asset URLs. Absent maps are `null`.
	albedo: string | null,
	normal: string | null,
	roughness_map: string | null,
	metallic_map: string | null,
	ao: string | null,
	emissive_map: string | null,
};

// One mesh the scene references, resolved to something loadable.
export type RenderMesh = {
	key: string,
	// `builtin` · `file` · `missing`
	source: string,
	// For `builtin`: the primitive name. For `file`: the absolute path.
	value: string,
};

export type ReviewSummary = {
	files: FileDiff[],
	total_additions: number,
	total_deletions: number,
	turn_title: string | null,
};

export type RiskLevel = "low" | "medium" | "high";

export type RuntimeBudgets = {
	instructions_per_tick: number,
	instructions_total: number,
	call_depth: number,
	spawned_entities: number,
	emitted_events: number,
	log_bytes: number,
	message_bytes: number,
	messages_per_tick: number,
	timers: number,
	heap_estimate_bytes: number,
	wall_clock_millis: number,
};

export type RuntimeCapability = "entity_read" | 
/**
 *  Mutate an entity that already exists: position, rotation, velocity, script vars.
 * 
 *  Deliberately does **not** cover creating or removing entities. Those are
 *  [`Self::EntityLifecycle`], because "nudge a velocity" and "delete the player" are not
 *  the same power and a generated mechanic that needs the first must not be handed the
 *  second (docs/15 §3.1).
 */
"entity_write_runtime" | 
// Bring an entity into existence or remove one. The genuinely lossy entity verb.
"entity_lifecycle" | "input_read" | "hud_action" | "level_travel" | "audio_event" | "deterministic_timer";

/**
 *  A persisted entity row shipped to the UI, with its stable hierarchy address
 *  (`scene:/Parent/Child#ULID`) resolved on the Rust side.
 */
export type SceneEntityView = {
	entity_id: EntityId,
	name: string,
	parent_id: EntityId | null,
	tags: string[],
	component_names: string[],
	stable_path: string,
};

export type SceneId = string;

export type SceneKind = "main" | "level" | "hud" | "empty";

// Scene-level settings (ambient, skybox). Values mirror what the Inspector can edit.
export type SceneSettings = {
	ambient?: [number, number, number],
	// `asset:<ulid>` reference to a skybox texture.
	skybox: string | null,
	// Unreal analogue: Main (persistent), Level, HUD, or an empty edit grid.
	kind?: SceneKind,
	// Path to the HUD scene (Main only).
	hud?: string | null,
	// Ordered playable levels (Main only).
	levels?: string[],
	// UltraSky-style weather preset id.
	weather?: string | null,
};

/**
 *  A persisted scene row as shipped to the UI: stable ULID id, path, kind and the
 *  number of entities, without the raw JSON payloads the AI inspects separately.
 */
export type SceneView = {
	scene_id: SceneId,
	rel_path: string,
	name: string,
	kind: string,
	entity_count: number,
	source_revision: number,
};

export type ScreenCapture = {
	origin_x: number,
	origin_y: number,
	width: number,
	height: number,
	image_base64: string,
	captured_at: string,
};

/**
 *  A located script failure — compile or runtime. Both carry a file and a line, because
 *  "your script is wrong" without a line is not a diagnostic.
 */
export type ScriptFault = {
	file: string,
	line: number,
	column: number,
	message: string,
	hint: string | null,
};

/**
 *  A compiled function: where its code starts, how many parameters it takes, and how many
 *  local slots its frame needs.
 */
export type ScriptFunction = {
	name: string,
	entry: number,
	params: number,
	locals: number,
	line: number,
};

// The four lifecycle hooks the runtime calls. A file may define any subset.
export type ScriptHook = "on_start" | "on_update" | "on_collision" | "on_trigger";

// One hook's entry point.
export type ScriptHookEntry = {
	hook: ScriptHook,
	function: number,
};

// A compiled script, ready to cross to the webview once, when play starts.
export type ScriptProgram = {
	file: string,
	code: Instr[],
	numbers: number[],
	strings: string[],
	functions: ScriptFunction[],
	/**
	 *  The host functions this program calls, in `CallHost.a` order. The VM binds these by
	 *  name, so the two languages share a vocabulary rather than an index.
	 */
	hosts: string[],
	hooks: ScriptHookEntry[],
	step_budget: number,
	call_depth: number,
};

// What kind of session a sidebar chip represents.
export type SessionKind = 
// A chat conversation with an AI agent.
"ai_chat" | 
/**
 *  A command-line shell tied to the project. Rendered client-side from stored
 *  CLI sessions; the engine only reports `AiChat` rows.
 */
"cli";

// Live state of a workspace session, derived from its last assistant turn.
export type SessionStatus = 
// A turn is queued or actively streaming.
"running" | 
// The agent is blocked on a permission request.
"paused" | 
// The last turn finished cleanly (done or stopped).
"idle" | 
// The last turn ended on a fault.
"failed";

// A recognized AI skill imported from a pre-installed AI app or defined by the user.
export type Skill = {
	id: string,
	name: string,
	description: string,
	prompt: string,
	// Source provider / app: "claude", "codex", "antigravity", "cursor", "workspace", "builtin", "custom"
	source: string,
	tags: string[],
	enabled: boolean,
	path: string | null,
};

/**
 *  Serializable search hit; mirrors the fields UI consumers need and drops the
 *  raw embedding blob (never shipped over IPC).
 */
export type SymbolHit = {
	kind: string,
	name: string,
	qualified_name: string,
	signature: string | null,
	start_line: number | null,
	end_line: number | null,
	stale: boolean,
};

// The terminal's child process exited.
export type TerminalExited = {
	id: string,
	exit_code: number | null,
};

// A chunk of terminal output, or the notice that the terminal has ended.
export type TerminalOutput = {
	id: string,
	// Base64 of the raw PTY bytes. Never decoded on this side — see the module docs.
	chunk: string,
};

// A newly opened terminal.
export type TerminalSession = {
	id: string,
	// Absolute directory the shell started in.
	cwd: string,
	shell: TerminalShell,
};

/**
 *  Shells a terminal can be opened with.
 * 
 *  The list is deliberately short: these are the hosts a program like opencode is
 *  launched *from*. The program itself is then typed at the prompt, exactly as it would
 *  be in Windows Terminal.
 */
export type TerminalShell = "powershell" | "cmd" | "git_bash" | "wsl" | 
// The platform's own default (`$SHELL` on Unix, PowerShell on Windows).
"system";

// The depth-ladder contract for one tier, IPC-shaped.
export type TierBudgetView = {
	tier: string,
	expansions: number,
	branch: number,
	sources_min: number,
	sources_max: number,
	min_tier2: number,
	min_primary: number,
	target_dots: number,
	counter_passes: number,
	timeline: boolean,
	entity_deep_dives: number,
	wall_minutes: number,
	tokens: number,
	words_min: number,
	words_max: number,
};

export type ToolAction = "plan" | "search_web" | "read_source" | "write_file" | "fetch_url" | "extract_dots" | "check_providers" | "control_computer" | "edit_engine";

/**
 *  One engine step shown inline in the assistant turn while it runs (CHT-100).
 * 
 *  A step used to be five strings — a label the transcript could print and nothing else.
 *  That is why an activity row could never expand: there was nothing behind it. The result
 *  fields below are what make "Ran commands ⌄" a disclosure rather than a decoration, and
 *  every one is optional, so a step with nothing to show renders exactly as it always did.
 */
export type ToolActivity = {
	id: string,
	action: ToolAction,
	title: string,
	detail: string,
	state: ToolState,
	// The command as it was actually run, when this step ran one.
	command?: string | null,
	// What it printed, already capped at capture (CHT-101).
	output?: string | null,
	// Present and non-zero is the interesting case; the transcript shows it then.
	exit_code?: number | null,
	// Wall-clock milliseconds this step took, filled in when it closes.
	elapsed_ms?: number | null,
	/**
	 *  Set when `output` is a middle-elided excerpt rather than the whole thing, so the
	 *  transcript can say so instead of quietly showing a partial answer as a full one.
	 */
	truncated?: boolean,
	// Files this step changed, with real line counts (CHT-104/105).
	changes?: TurnFileChange[],
};

export type ToolAvailability = {
	tool: ProjectTool,
	label: string,
	available: boolean,
	hint: string,
};

export type ToolState = "running" | "ok" | "failed" | "skipped";

export type ToolStatus = {
	tool: string,
	at: string,
	ok: boolean,
	note: string | null,
};

// What a whole turn changed on disk (CHT-104).
export type TurnChanges = {
	files: TurnFileChange[],
	total_additions: number,
	total_deletions: number,
};

/**
 *  A named failure, with the one action that resolves it.
 * 
 *  The string `error` beside this stays for anything that wants the raw text, but a
 *  string cannot be rendered as a card with a button on it, and "provider unavailable"
 *  is not a sentence any user can act on. Every field here exists because the UI needs
 *  it to show a specific remedy rather than a generic apology.
 */
export type TurnFault = {
	// Stable id — `context_exceeded`, `rate_limited_weekly`, and so on.
	kind: string,
	// Headline naming the failure, not the symptom.
	title: string,
	// One sentence on what happened.
	summary: string,
	// The next concrete action, in prose.
	fix: string,
	/**
	 *  Which button to offer: `compact`, `update`, `switch_provider`, `sign_in`,
	 *  `retry`, or `none`.
	 */
	remedy: string,
	action_label: string | null,
	// The provider that failed, by its display label.
	provider: string,
	// The vendor's own reset wording, when it named one.
	resets_at: string | null,
	// Whether sending the same message again could plausibly work.
	retryable: boolean,
	// What the vendor actually said, kept for the "details" disclosure.
	detail: string,
};

// One file a turn changed, and by how much.
export type TurnFileChange = {
	// Workspace-relative, forward-slashed — the path the transcript prints.
	path: string,
	additions: number,
	deletions: number,
	// `added` | `modified` | `deleted`, matching `bhippi-app::review`.
	status: string,
};

/**
 *  A transcript notice — a usage limit, a rate limit, a provider warning (CHT-106).
 * 
 *  These used to have nowhere to go: only a *fault* rendered, so "you have hit your usage
 *  limit" either became a fake failure or vanished.
 */
export type TurnNotice = {
	level: NoticeLevel,
	message: string,
	hint?: string | null,
};

export type TurnPair = {
	conversation_id: string,
	user_turn_id: string,
	assistant_turn_id: string,
};

export type TurnState = "queued" | "streaming" | "awaiting_permission" | "done" | "stopped" | "failed";

export type Usage = {
	input_tokens: number,
	output_tokens: number,
};

// One column of the usage chart.
export type UsageDayPoint = {
	// `YYYY-MM-DD`, local time.
	date: string,
	total_tokens: number,
	cost_usd: number,
	/**
	 *  Only the providers that actually spent something that day — a zero row would be
	 *  a line drawn along the axis for a backend that was not even running.
	 */
	providers: DayProviderPoint[],
};

// Everything the gauge, its drop-up, and Settings › Usage need in one read.
export type UsageSummary = {
	window: UsageWindow,
	window_label: string,
	active_provider_id: string,
	// The provider the ring reports on — present even when it has spent nothing.
	active: ProviderUsage,
	// Every provider with history in the window, plus every enabled one, heaviest first.
	providers: ProviderUsage[],
	total_tokens: number,
	total_input_tokens: number,
	total_output_tokens: number,
	total_cost_usd: number,
	total_turns: number,
	// Mean tokens per answered turn in the window; `0` when nothing was answered.
	tokens_per_turn: number,
	// The window's span as the header prints it, e.g. `28 Jul – 26 Aug`.
	range_label: string,
	// Seconds until the daily window rolls over at local midnight.
	resets_in_seconds: number,
	// Oldest to newest, zero-filled — `window.chart_days()` entries.
	days: UsageDayPoint[],
};

// The span a usage figure covers.
export type UsageWindow = "day" | "week" | "month" | 
// The whole retained history (`bhippi_core::RETAINED_DAYS`).
"quarter";

/**
 *  One weather preset. `sky` is a packed `0xRRGGBB` the viewport paints the dome with;
 *  `fog` is a 0..1 density the renderer scales its own fog range by.
 */
export type WeatherPreset = {
	id: string,
	label: string,
	ambient: [number, number, number],
	// Intensity written onto every `directional` light in the scene.
	sun: number,
	fog: number,
	sky: number,
	// `none` · `rain` · `snow` — the overlay particle system the viewport runs.
	precip: string,
};

// One row in the workbench file tree.
export type WorkspaceEntry = {
	// Display name — the final path segment.
	name: string,
	// Project-relative path with `/` separators, stable across platforms.
	path: string,
	is_directory: boolean,
	// Byte length for files; `0` for directories, which are not measured.
	size: number,
	/**
	 *  True when the directory holds at least one visible entry, so the tree can draw
	 *  a disclosure chevron without listing the children first.
	 */
	has_children: boolean,
};

// A file the editor has opened.
export type WorkspaceFile = {
	path: string,
	name: string,
	text: string,
	bytes: number,
	// True when the file was too large to load; saving is refused for these.
	truncated: boolean,
	// Lowercase extension, or an empty string — the highlighter's only input.
	language: string,
	// False when the file is too large or not text; the editor then opens read-only.
	editable: boolean,
	// Base64-encoded content for binary files (images, etc.). `None` for text files.
	content_base64: string | null,
};

/**
 *  One session per project, as the workspace rail renders it. The command layer
 *  enriches `provider` with the catalogue id after mapping the label the turn stores
 *  to a known backend, so the icon renders for real providers and falls back to a
 *  generic chat mark otherwise.
 */
export type WorkspaceSession = {
	id: string,
	project_path: string,
	kind: SessionKind,
	title: string,
	// Catalogue provider id (`claude`, `codex`, `demo`, …) — drives the icon.
	provider: string | null,
	// Human-readable provider label from the last assistant turn, for tooltips.
	provider_label: string | null,
	status: SessionStatus,
	created_at: string,
	updated_at: string,
	turn_count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

