//! External generative asset providers and explicit adapters (ADR-0043, GAD-115, GAD-116).
//!
//! Provides the [`AssetProvider`] trait for generative image, 3D mesh, and audio models.
//! External generation is strictly opt-in (never silent) and attaches the provider's
//! verbatim licence terms to every output sidecar (INV-074).

use async_trait::async_trait;
use bhippi_types::{BhippiError, Result};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;

/// Capabilities an asset provider can fulfill.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AssetCapability {
    TextImage,
    Text3D,
    TextAudio,
}

/// The core trait for external generative asset backends.
#[async_trait]
pub trait AssetProvider: Send + Sync {
    fn id(&self) -> &str;
    fn name(&self) -> &str;
    fn capabilities(&self) -> &[AssetCapability];
    fn license_terms(&self) -> &str;
    fn is_enabled(&self) -> bool;
    fn calls_made(&self) -> u64;

    async fn generate_image(&self, prompt: &str, style: Option<&str>) -> Result<Vec<u8>>;
    async fn generate_mesh(&self, prompt: &str, style: Option<&str>) -> Result<String>;
    async fn generate_audio(&self, prompt: &str) -> Result<Vec<u8>>;
}

/// Local image endpoint adapter (e.g. Ollama or local ComfyUI). Gated by explicit enablement.
pub struct LocalImageProvider {
    id: String,
    name: String,
    endpoint: String,
    enabled: Arc<AtomicBool>,
    calls: Arc<AtomicU64>,
    license_terms: String,
}

impl LocalImageProvider {
    #[must_use]
    pub fn new(endpoint: &str, enabled: bool) -> Self {
        Self {
            id: "local_image_generator".to_owned(),
            name: "Local Image Generator (Ollama / ComfyUI)".to_owned(),
            endpoint: endpoint.to_owned(),
            enabled: Arc::new(AtomicBool::new(enabled)),
            calls: Arc::new(AtomicU64::new(0)),
            license_terms: "Generated by local weights; license governed by loaded model weights."
                .to_owned(),
        }
    }

    pub fn set_enabled(&self, state: bool) {
        self.enabled.store(state, Ordering::SeqCst);
    }
}

#[async_trait]
impl AssetProvider for LocalImageProvider {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn capabilities(&self) -> &[AssetCapability] {
        &[AssetCapability::TextImage]
    }

    fn license_terms(&self) -> &str {
        &self.license_terms
    }

    fn is_enabled(&self) -> bool {
        self.enabled.load(Ordering::Relaxed)
    }

    fn calls_made(&self) -> u64 {
        self.calls.load(Ordering::Relaxed)
    }

    async fn generate_image(&self, prompt: &str, _style: Option<&str>) -> Result<Vec<u8>> {
        if !self.is_enabled() {
            return Err(BhippiError::Provider {
                id: self.id.clone(),
                reason: "local image provider is disabled; enable it explicitly in Settings"
                    .to_owned(),
                retryable: false,
                hint: Some("Enable external generation in Settings -> Add-ons.".to_owned()),
            });
        }

        self.calls.fetch_add(1, Ordering::SeqCst);

        // Fallback or local simulation byte response when offline/testing
        if self.endpoint.starts_with("mock://") || self.endpoint.is_empty() {
            // Return minimal 1x1 test PNG
            return Ok(vec![
                0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, b'I', b'H',
                b'D', b'R', 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00,
                0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0A, b'I', b'D', b'A', b'T', 0x78,
                0x01, 0x63, 0x60, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x49,
                0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
            ]);
        }

        Err(BhippiError::Provider {
            id: self.id.clone(),
            reason: format!(
                "endpoint {} connection timeout for prompt {:?}",
                self.endpoint, prompt
            ),
            retryable: true,
            hint: Some("Check that the local generation service is running.".to_owned()),
        })
    }

    async fn generate_mesh(&self, _prompt: &str, _style: Option<&str>) -> Result<String> {
        Err(BhippiError::Provider {
            id: self.id.clone(),
            reason: "mesh generation unsupported by image provider".to_owned(),
            retryable: false,
            hint: None,
        })
    }

    async fn generate_audio(&self, _prompt: &str) -> Result<Vec<u8>> {
        Err(BhippiError::Provider {
            id: self.id.clone(),
            reason: "audio generation unsupported by image provider".to_owned(),
            retryable: false,
            hint: None,
        })
    }
}

/// Cloud Text-to-3D adapter stub behind explicit enable.
pub struct CloudText3DProvider {
    id: String,
    name: String,
    enabled: Arc<AtomicBool>,
    calls: Arc<AtomicU64>,
    license_terms: String,
}

impl CloudText3DProvider {
    #[must_use]
    pub fn new(enabled: bool) -> Self {
        Self {
            id: "cloud_3d_generator".to_owned(),
            name: "Cloud Text-to-3D Service".to_owned(),
            enabled: Arc::new(AtomicBool::new(enabled)),
            calls: Arc::new(AtomicU64::new(0)),
            license_terms: "Royalty-free commercial game asset license from generative provider."
                .to_owned(),
        }
    }

    pub fn set_enabled(&self, state: bool) {
        self.enabled.store(state, Ordering::SeqCst);
    }
}

#[async_trait]
impl AssetProvider for CloudText3DProvider {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn capabilities(&self) -> &[AssetCapability] {
        &[AssetCapability::Text3D]
    }

    fn license_terms(&self) -> &str {
        &self.license_terms
    }

    fn is_enabled(&self) -> bool {
        self.enabled.load(Ordering::Relaxed)
    }

    fn calls_made(&self) -> u64 {
        self.calls.load(Ordering::Relaxed)
    }

    async fn generate_image(&self, _prompt: &str, _style: Option<&str>) -> Result<Vec<u8>> {
        Err(BhippiError::Provider {
            id: self.id.clone(),
            reason: "image generation unsupported by 3D provider".to_owned(),
            retryable: false,
            hint: None,
        })
    }

    async fn generate_mesh(&self, prompt: &str, _style: Option<&str>) -> Result<String> {
        if !self.is_enabled() {
            return Err(BhippiError::Provider {
                id: self.id.clone(),
                reason: "cloud 3D provider is disabled; enable it explicitly in Settings"
                    .to_owned(),
                retryable: false,
                hint: Some("Enable external 3D generation in Settings -> Add-ons.".to_owned()),
            });
        }

        self.calls.fetch_add(1, Ordering::SeqCst);

        // Deterministic low-poly Godot 4 scene proxy for prompt
        Ok(format!(
            r#"[gd_scene format=3 uid="uid://cloud_mesh_{:x}"]

[node name="GeneratedModel" type="Node3D"]

[node name="Shape" type="CSGBox3D" parent="."]
size = Vector3(1.2, 1.2, 1.2)
use_collision = true
"#,
            prompt
                .bytes()
                .fold(0u32, |acc, b| acc.wrapping_mul(31).wrapping_add(b as u32))
        ))
    }

    async fn generate_audio(&self, _prompt: &str) -> Result<Vec<u8>> {
        Err(BhippiError::Provider {
            id: self.id.clone(),
            reason: "audio generation unsupported by 3D provider".to_owned(),
            retryable: false,
            hint: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn disabled_provider_refuses_generation() {
        let provider = LocalImageProvider::new("mock://test", false);
        assert!(!provider.is_enabled());
        let res = provider.generate_image("a red ball", None).await;
        assert!(res.is_err());
        assert_eq!(provider.calls_made(), 0);
    }

    #[tokio::test]
    async fn enabled_provider_generates_and_increments_calls() {
        let provider = LocalImageProvider::new("mock://test", true);
        assert!(provider.is_enabled());
        let bytes = provider
            .generate_image("a blue square", None)
            .await
            .unwrap();
        assert!(!bytes.is_empty());
        assert_eq!(provider.calls_made(), 1);
        assert!(provider.license_terms().contains("license"));
    }

    #[tokio::test]
    async fn cloud_3d_provider_generates_scene_when_enabled() {
        let provider = CloudText3DProvider::new(true);
        let tscn = provider.generate_mesh("castle tower", None).await.unwrap();
        assert!(tscn.contains("GeneratedModel"));
        assert_eq!(provider.calls_made(), 1);
    }
}
