//! Procedural mesh generation from Godot CSG nodes and primitives (ADR-0043, GAD-110).
//!
//! Generates deterministic, valid Godot 4 `.tscn` scenes for common 3D structural
//! archetypes (buildings, trees, rocks, crates, fences, vehicles, islands) without
//! requiring 3D modelling tools or external asset downloads.

use crate::error::{EngineError, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Supported procedural mesh kinds.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ProceduralMeshPreset {
    Building,
    Tree,
    Rock,
    Crate,
    Fence,
    VehiclePrimitive,
    Island,
}

impl ProceduralMeshPreset {
    #[must_use]
    pub fn parse(tag: &str) -> Option<Self> {
        match tag.to_ascii_lowercase().as_str() {
            "building" | "house" | "structure" | "tower" => Some(Self::Building),
            "tree" | "pine" | "foliage" | "plant" => Some(Self::Tree),
            "rock" | "boulder" | "stone" => Some(Self::Rock),
            "crate" | "box" | "container" | "barrel" => Some(Self::Crate),
            "fence" | "barrier" | "wall_low" => Some(Self::Fence),
            "vehicle" | "car" | "kart" | "vehicle_primitive" => Some(Self::VehiclePrimitive),
            "island" | "terrain_chunk" | "platform" => Some(Self::Island),
            _ => None,
        }
    }
}

/// Generated procedural mesh artefact.
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratedMesh {
    pub name: String,
    pub rel_path: String,
    pub tscn_content: String,
    pub sidecar_content: String,
}

/// Generate a deterministic Godot 4 `.tscn` scene for the requested preset.
pub fn generate_procedural_mesh(
    name: &str,
    preset: ProceduralMeshPreset,
    seed: u64,
) -> Result<GeneratedMesh> {
    let clean_name = if name.trim().is_empty() {
        "procedural_mesh"
    } else {
        name.trim()
    };
    let file_name = format!("{clean_name}.tscn");
    let rel_path = format!("assets/models/{file_name}");

    let tscn = match preset {
        ProceduralMeshPreset::Building => generate_building_tscn(clean_name, seed),
        ProceduralMeshPreset::Tree => generate_tree_tscn(clean_name, seed),
        ProceduralMeshPreset::Rock => generate_rock_tscn(clean_name, seed),
        ProceduralMeshPreset::Crate => generate_crate_tscn(clean_name, seed),
        ProceduralMeshPreset::Fence => generate_fence_tscn(clean_name, seed),
        ProceduralMeshPreset::VehiclePrimitive => generate_vehicle_tscn(clean_name, seed),
        ProceduralMeshPreset::Island => generate_island_tscn(clean_name, seed),
    };

    let now = chrono::Utc::now().to_rfc3339();
    let sidecar = serde_json::json!({
        "license": "project",
        "provenance": {
            "source": "procedural",
            "generator": "bhippi-procedural-mesh",
            "preset": format!("{preset:?}").to_lowercase(),
            "seed": seed
        },
        "created_at": now,
        "attribution": "Procedurally generated by Bhippi Studio (ADR-0043)"
    });

    let sidecar_content = serde_json::to_string_pretty(&sidecar).map_err(|error| {
        EngineError::Asset(
            format!("failed to format sidecar: {error}"),
            Some("Report this as an engine bug.".to_owned()),
        )
    })?;

    Ok(GeneratedMesh {
        name: clean_name.to_owned(),
        rel_path,
        tscn_content: tscn,
        sidecar_content,
    })
}

/// Write the generated mesh and its `.meta.json` sidecar to a project directory.
pub fn write_procedural_mesh(game_dir: &Path, mesh: &GeneratedMesh) -> Result<()> {
    let tscn_path = game_dir.join(&mesh.rel_path);
    let meta_path = game_dir.join(format!("{}.meta.json", mesh.rel_path));

    if let Some(parent) = tscn_path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| EngineError::Io {
            operation: "create_dir_all",
            path: parent.display().to_string(),
            reason: error.to_string(),
            hint: Some("Check workspace write permissions.".to_owned()),
        })?;
    }

    std::fs::write(&tscn_path, &mesh.tscn_content).map_err(|error| EngineError::Io {
        operation: "write",
        path: tscn_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace disk space and permissions.".to_owned()),
    })?;

    std::fs::write(&meta_path, &mesh.sidecar_content).map_err(|error| EngineError::Io {
        operation: "write",
        path: meta_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace permissions.".to_owned()),
    })?;

    Ok(())
}

fn generate_building_tscn(name: &str, seed: u64) -> String {
    let height = 3.0 + ((seed % 5) as f32) * 0.5;
    let width = 4.0 + ((seed / 5 % 3) as f32) * 0.5;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_bld_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="Combiner" type="CSGCombiner3D" parent="."]
use_collision = true

[node name="Walls" type="CSGBox3D" parent="Combiner"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {y_mid:.2}, 0)
size = Vector3({width:.2}, {height:.2}, 4.0)

[node name="Roof" type="CSGPolygon3D" parent="Combiner"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -{half_w:.2}, {height:.2}, 2.0)
polygon = PackedVector2Array(0, 0, {half_w:.2}, 1.5, {width:.2}, 0)
depth = 4.0
"#,
        y_mid = height / 2.0,
        half_w = width / 2.0,
    )
}

fn generate_tree_tscn(name: &str, seed: u64) -> String {
    let trunk_h = 1.5 + ((seed % 3) as f32) * 0.25;
    let foliage_r = 1.2 + ((seed / 3 % 4) as f32) * 0.2;
    let top_y = trunk_h + foliage_r * 0.8;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_tre_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="Trunk" type="CSGCylinder3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {trunk_mid:.2}, 0)
radius = 0.2
height = {trunk_h:.2}
sides = 8
use_collision = true

[node name="Foliage" type="CSGSphere3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {top_y:.2}, 0)
radius = {foliage_r:.2}
radial_segments = 8
rings = 6
"#,
        trunk_mid = trunk_h / 2.0,
    )
}

fn generate_rock_tscn(name: &str, seed: u64) -> String {
    let scale_x = 0.8 + ((seed % 4) as f32) * 0.15;
    let scale_y = 0.7 + ((seed / 4 % 3) as f32) * 0.15;
    let scale_z = 0.9 + ((seed / 12 % 3) as f32) * 0.15;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_rck_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="RockShape" type="CSGSphere3D" parent="."]
transform = Transform3D({scale_x:.2}, 0, 0, 0, {scale_y:.2}, 0, 0, 0, {scale_z:.2}, 0, {y:.2}, 0)
radius = 1.0
radial_segments = 6
rings = 4
use_collision = true
"#,
        y = scale_y * 0.8,
    )
}

fn generate_crate_tscn(name: &str, seed: u64) -> String {
    let size = 1.0 + ((seed % 3) as f32) * 0.2;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_crt_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="Box" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {y:.2}, 0)
size = Vector3({size:.2}, {size:.2}, {size:.2})
use_collision = true
"#,
        y = size / 2.0,
    )
}

fn generate_fence_tscn(name: &str, seed: u64) -> String {
    let length = 3.0 + ((seed % 3) as f32) * 0.5;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_fnc_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="PostL" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -{half_l:.2}, 0.6, 0)
size = Vector3(0.15, 1.2, 0.15)
use_collision = true

[node name="PostR" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {half_l:.2}, 0.6, 0)
size = Vector3(0.15, 1.2, 0.15)
use_collision = true

[node name="RailUpper" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
size = Vector3({length:.2}, 0.1, 0.08)

[node name="RailLower" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.4, 0)
size = Vector3({length:.2}, 0.1, 0.08)
"#,
        half_l = length / 2.0,
    )
}

fn generate_vehicle_tscn(name: &str, seed: u64) -> String {
    let length = 2.4 + ((seed % 3) as f32) * 0.3;
    let width = 1.4;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_veh_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="Chassis" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.45, 0)
size = Vector3({width:.2}, 0.5, {length:.2})
use_collision = true

[node name="Cabin" type="CSGBox3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, -0.2)
size = Vector3(1.1, 0.5, 1.2)

[node name="WheelFL" type="CSGCylinder3D" parent="."]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, 0.75, 0.25, 0.8)
radius = 0.25
height = 0.15

[node name="WheelFR" type="CSGCylinder3D" parent="."]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, -0.75, 0.25, 0.8)
radius = 0.25
height = 0.15

[node name="WheelRL" type="CSGCylinder3D" parent="."]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, 0.75, 0.25, -0.8)
radius = 0.25
height = 0.15

[node name="WheelRR" type="CSGCylinder3D" parent="."]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, -0.75, 0.25, -0.8)
radius = 0.25
height = 0.15
"#
    )
}

fn generate_island_tscn(name: &str, seed: u64) -> String {
    let radius = 6.0 + ((seed % 4) as f32) * 1.5;
    format!(
        r#"[gd_scene format=3 uid="uid://proc_isl_{seed:x}"]

[node name="{name}" type="Node3D"]

[node name="Platform" type="CSGCylinder3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.5, 0)
radius = {radius:.2}
height = 1.0
sides = 12
use_collision = true

[node name="Base" type="CSGCylinder3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.75, 0)
radius = {base_r:.2}
height = 1.5
sides = 8
"#,
        base_r = radius * 0.7,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedural_mesh_generates_valid_tscn_and_sidecar() {
        let mesh = generate_procedural_mesh("PineTree", ProceduralMeshPreset::Tree, 42).unwrap();
        assert!(mesh
            .tscn_content
            .contains("[node name=\"PineTree\" type=\"Node3D\"]"));
        assert!(mesh.tscn_content.contains("CSGCylinder3D"));
        assert!(mesh.tscn_content.contains("CSGSphere3D"));
        assert!(mesh.sidecar_content.contains("\"license\": \"project\""));
        assert!(mesh.sidecar_content.contains("\"preset\": \"tree\""));
        assert!(mesh.rel_path.starts_with("assets/models/"));
    }

    #[test]
    fn presets_parse_from_common_tags() {
        assert_eq!(
            ProceduralMeshPreset::parse("pine"),
            Some(ProceduralMeshPreset::Tree)
        );
        assert_eq!(
            ProceduralMeshPreset::parse("house"),
            Some(ProceduralMeshPreset::Building)
        );
        assert_eq!(
            ProceduralMeshPreset::parse("boulder"),
            Some(ProceduralMeshPreset::Rock)
        );
        assert_eq!(
            ProceduralMeshPreset::parse("crate"),
            Some(ProceduralMeshPreset::Crate)
        );
        assert_eq!(
            ProceduralMeshPreset::parse("car"),
            Some(ProceduralMeshPreset::VehiclePrimitive)
        );
        assert_eq!(
            ProceduralMeshPreset::parse("island"),
            Some(ProceduralMeshPreset::Island)
        );
    }
}
