//! Procedural SFX synthesis baked to 16-bit PCM WAV (ADR-0043, GAD-112).
//!
//! Generates classic arcade and retro sound effects (jump, coin, hit, blip, explosion)
//! deterministically without external sound samples or runtime audio engines.

use crate::error::{EngineError, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Supported procedural sound effects.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ProceduralAudioPreset {
    Jump,
    Coin,
    Hit,
    Blip,
    Explosion,
}

impl ProceduralAudioPreset {
    #[must_use]
    pub fn parse(tag: &str) -> Option<Self> {
        match tag.to_ascii_lowercase().as_str() {
            "jump" | "hop" | "leap" => Some(Self::Jump),
            "coin" | "pickup" | "chime" | "collect" => Some(Self::Coin),
            "hit" | "hurt" | "damage" | "impact" => Some(Self::Hit),
            "blip" | "beep" | "ui" | "click" => Some(Self::Blip),
            "explosion" | "boom" | "blast" | "crash" => Some(Self::Explosion),
            _ => None,
        }
    }
}

/// Generated audio artefact with WAV bytes and `.meta.json` sidecar.
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratedAudio {
    pub name: String,
    pub rel_path: String,
    pub wav_bytes: Vec<u8>,
    pub sidecar_content: String,
    pub duration_seconds: f32,
    pub sample_rate: u32,
}

const SAMPLE_RATE: u32 = 22050;

/// Generate a deterministic 16-bit PCM WAV audio effect for the requested preset.
pub fn generate_procedural_audio(
    name: &str,
    preset: ProceduralAudioPreset,
    seed: u64,
) -> Result<GeneratedAudio> {
    let clean_name = if name.trim().is_empty() {
        "procedural_audio"
    } else {
        name.trim()
    };
    let file_name = format!("{clean_name}.wav");
    let rel_path = format!("assets/audio/{file_name}");

    let samples = match preset {
        ProceduralAudioPreset::Jump => synthesize_jump(SAMPLE_RATE, seed),
        ProceduralAudioPreset::Coin => synthesize_coin(SAMPLE_RATE, seed),
        ProceduralAudioPreset::Hit => synthesize_hit(SAMPLE_RATE, seed),
        ProceduralAudioPreset::Blip => synthesize_blip(SAMPLE_RATE, seed),
        ProceduralAudioPreset::Explosion => synthesize_explosion(SAMPLE_RATE, seed),
    };

    let duration_seconds = samples.len() as f32 / SAMPLE_RATE as f32;
    let wav_bytes = encode_wav(SAMPLE_RATE, &samples)?;

    let now = chrono::Utc::now().to_rfc3339();
    let sidecar = serde_json::json!({
        "license": "project",
        "provenance": {
            "source": "procedural",
            "generator": "bhippi-procedural-audio",
            "preset": format!("{preset:?}").to_lowercase(),
            "sample_rate": SAMPLE_RATE,
            "duration_seconds": duration_seconds,
            "seed": seed
        },
        "created_at": now,
        "attribution": "Procedurally generated by Bhippi Studio (ADR-0043)"
    });

    let sidecar_content = serde_json::to_string_pretty(&sidecar).map_err(|error| {
        EngineError::Asset(
            format!("failed to format audio sidecar: {error}"),
            Some("Report this as an engine bug.".to_owned()),
        )
    })?;

    Ok(GeneratedAudio {
        name: clean_name.to_owned(),
        rel_path,
        wav_bytes,
        sidecar_content,
        duration_seconds,
        sample_rate: SAMPLE_RATE,
    })
}

/// Write the generated audio and its `.meta.json` sidecar to a project directory.
pub fn write_procedural_audio(game_dir: &Path, audio: &GeneratedAudio) -> Result<()> {
    let wav_path = game_dir.join(&audio.rel_path);
    let meta_path = game_dir.join(format!("{}.meta.json", audio.rel_path));

    if let Some(parent) = wav_path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| EngineError::Io {
            operation: "create_dir_all",
            path: parent.display().to_string(),
            reason: error.to_string(),
            hint: Some("Check workspace write permissions.".to_owned()),
        })?;
    }

    std::fs::write(&wav_path, &audio.wav_bytes).map_err(|error| EngineError::Io {
        operation: "write",
        path: wav_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace disk space and permissions.".to_owned()),
    })?;

    std::fs::write(&meta_path, &audio.sidecar_content).map_err(|error| EngineError::Io {
        operation: "write",
        path: meta_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace permissions.".to_owned()),
    })?;

    Ok(())
}

fn prng(state: &mut u64) -> f32 {
    *state = state
        .wrapping_mul(6364136223846793005)
        .wrapping_add(1442695040888963407);
    let u = ((*state >> 32) & 0xFFFFFFFF) as f32;
    (u / 4294967295.0) * 2.0 - 1.0
}

fn synthesize_jump(sample_rate: u32, seed: u64) -> Vec<i16> {
    let duration = 0.28;
    let total_samples = (sample_rate as f32 * duration) as usize;
    let mut samples = Vec::with_capacity(total_samples);
    let mut phase = 0.0f32;
    let base_freq = 160.0 + ((seed % 40) as f32);
    let end_freq = 520.0;

    for i in 0..total_samples {
        let t = i as f32 / total_samples as f32;
        let freq = base_freq + (end_freq - base_freq) * (t * t);
        phase += 2.0 * std::f32::consts::PI * freq / sample_rate as f32;
        let env = if t < 0.1 {
            t / 0.1
        } else {
            (1.0 - t).powf(1.2)
        };
        let square = if phase.sin() >= 0.0 { 0.7 } else { -0.7 };
        let sample = (square * env * 24000.0) as i16;
        samples.push(sample);
    }
    samples
}

fn synthesize_coin(sample_rate: u32, seed: u64) -> Vec<i16> {
    let duration = 0.35;
    let total_samples = (sample_rate as f32 * duration) as usize;
    let split = (total_samples as f32 * 0.28) as usize;
    let mut samples = Vec::with_capacity(total_samples);
    let mut phase = 0.0f32;
    let freq1 = 987.77 + ((seed % 20) as f32); // B5
    let freq2 = 1318.51; // E6

    for i in 0..total_samples {
        let (freq, env) = if i < split {
            let t = i as f32 / split as f32;
            (freq1, 1.0 - t * 0.3)
        } else {
            let t = (i - split) as f32 / (total_samples - split) as f32;
            (freq2, (1.0 - t).powf(1.8))
        };
        phase += 2.0 * std::f32::consts::PI * freq / sample_rate as f32;
        let sample = (phase.sin() * env * 26000.0) as i16;
        samples.push(sample);
    }
    samples
}

fn synthesize_hit(sample_rate: u32, seed: u64) -> Vec<i16> {
    let duration = 0.22;
    let total_samples = (sample_rate as f32 * duration) as usize;
    let mut samples = Vec::with_capacity(total_samples);
    let mut rng_state = seed.wrapping_add(987654321);

    for i in 0..total_samples {
        let t = i as f32 / total_samples as f32;
        let noise = prng(&mut rng_state);
        let env = (1.0 - t).powf(2.5);
        let sample = (noise * env * 28000.0) as i16;
        samples.push(sample);
    }
    samples
}

fn synthesize_blip(sample_rate: u32, seed: u64) -> Vec<i16> {
    let duration = 0.05;
    let total_samples = (sample_rate as f32 * duration) as usize;
    let mut samples = Vec::with_capacity(total_samples);
    let mut phase = 0.0f32;
    let freq = 440.0 + ((seed % 80) as f32);

    for i in 0..total_samples {
        let t = i as f32 / total_samples as f32;
        phase += 2.0 * std::f32::consts::PI * freq / sample_rate as f32;
        let env = (1.0 - t).powf(0.8);
        let sample = (phase.sin() * env * 22000.0) as i16;
        samples.push(sample);
    }
    samples
}

fn synthesize_explosion(sample_rate: u32, seed: u64) -> Vec<i16> {
    let duration = 0.55;
    let total_samples = (sample_rate as f32 * duration) as usize;
    let mut samples = Vec::with_capacity(total_samples);
    let mut rng_state = seed.wrapping_add(135792468);
    let mut rumble_phase = 0.0f32;

    for i in 0..total_samples {
        let t = i as f32 / total_samples as f32;
        let noise = prng(&mut rng_state);
        rumble_phase += 2.0 * std::f32::consts::PI * 65.0 / sample_rate as f32;
        let rumble = rumble_phase.sin() * 0.4;
        let env = (1.0 - t).powf(1.6);
        let sample = ((noise * 0.7 + rumble) * env * 28000.0).clamp(-32767.0, 32767.0) as i16;
        samples.push(sample);
    }
    samples
}

fn encode_wav(sample_rate: u32, samples: &[i16]) -> Result<Vec<u8>> {
    let num_channels = 1u16;
    let bits_per_sample = 16u16;
    let byte_rate = sample_rate * num_channels as u32 * (bits_per_sample / 8) as u32;
    let block_align = num_channels * (bits_per_sample / 8);
    let data_len = (samples.len() * 2) as u32;
    let file_len = 36 + data_len;

    let mut wav = Vec::with_capacity((44 + data_len) as usize);
    // RIFF Chunk
    wav.extend_from_slice(b"RIFF");
    wav.extend_from_slice(&file_len.to_le_bytes());
    wav.extend_from_slice(b"WAVE");

    // Format subchunk
    wav.extend_from_slice(b"fmt ");
    wav.extend_from_slice(&16u32.to_le_bytes()); // Subchunk1Size for PCM
    wav.extend_from_slice(&1u16.to_le_bytes()); // AudioFormat 1 = PCM
    wav.extend_from_slice(&num_channels.to_le_bytes());
    wav.extend_from_slice(&sample_rate.to_le_bytes());
    wav.extend_from_slice(&byte_rate.to_le_bytes());
    wav.extend_from_slice(&block_align.to_le_bytes());
    wav.extend_from_slice(&bits_per_sample.to_le_bytes());

    // Data subchunk
    wav.extend_from_slice(b"data");
    wav.extend_from_slice(&data_len.to_le_bytes());
    for &sample in samples {
        wav.extend_from_slice(&sample.to_le_bytes());
    }

    Ok(wav)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedural_audio_generates_valid_wav_header_and_sidecar() {
        let audio =
            generate_procedural_audio("CoinSound", ProceduralAudioPreset::Coin, 42).unwrap();
        assert_eq!(&audio.wav_bytes[0..4], b"RIFF");
        assert_eq!(&audio.wav_bytes[8..12], b"WAVE");
        assert_eq!(&audio.wav_bytes[12..16], b"fmt ");
        assert_eq!(&audio.wav_bytes[36..40], b"data");
        assert!(audio.sidecar_content.contains("\"license\": \"project\""));
        assert!(audio.sidecar_content.contains("\"preset\": \"coin\""));
        assert!(audio.duration_seconds > 0.1);
    }

    #[test]
    fn all_audio_presets_generate_wav() {
        let presets = [
            ProceduralAudioPreset::Jump,
            ProceduralAudioPreset::Coin,
            ProceduralAudioPreset::Hit,
            ProceduralAudioPreset::Blip,
            ProceduralAudioPreset::Explosion,
        ];
        for preset in presets {
            let res = generate_procedural_audio("snd", preset, 10).unwrap();
            assert!(res.wav_bytes.len() > 100);
            assert_eq!(&res.wav_bytes[0..4], b"RIFF");
        }
    }
}
