//! Procedural texture generation baked to standard PNG (ADR-0043, GAD-111).
//!
//! Generates deterministic, valid PNG images for common game materials (noise,
//! stripes, bricks, wood, metal, grass) completely in pure, safe Rust.

use crate::error::{EngineError, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Supported procedural texture patterns.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ProceduralTexturePattern {
    Noise,
    Stripes,
    Bricks,
    Wood,
    Metal,
    Grass,
}

impl ProceduralTexturePattern {
    #[must_use]
    pub fn parse(tag: &str) -> Option<Self> {
        match tag.to_ascii_lowercase().as_str() {
            "noise" | "dirt" | "ground" | "cloud" => Some(Self::Noise),
            "stripes" | "checkered" | "pattern" => Some(Self::Stripes),
            "brick" | "bricks" | "stone_wall" | "tile" => Some(Self::Bricks),
            "wood" | "plank" | "bark" => Some(Self::Wood),
            "metal" | "steel" | "iron" | "chrome" => Some(Self::Metal),
            "grass" | "lawn" | "moss" => Some(Self::Grass),
            _ => None,
        }
    }
}

/// Generated texture with PNG bytes and `.meta.json` sidecar.
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratedTexture {
    pub name: String,
    pub rel_path: String,
    pub png_bytes: Vec<u8>,
    pub sidecar_content: String,
    pub width: u32,
    pub height: u32,
}

/// Generate a deterministic PNG texture of given dimensions and pattern.
pub fn generate_procedural_texture(
    name: &str,
    pattern: ProceduralTexturePattern,
    width: u32,
    height: u32,
    seed: u64,
) -> Result<GeneratedTexture> {
    let clean_name = if name.trim().is_empty() {
        "procedural_texture"
    } else {
        name.trim()
    };
    let file_name = format!("{clean_name}.png");
    let rel_path = format!("assets/textures/{file_name}");

    let w = width.clamp(16, 1024);
    let h = height.clamp(16, 1024);

    let rgba_pixels = match pattern {
        ProceduralTexturePattern::Noise => generate_noise(w, h, seed),
        ProceduralTexturePattern::Stripes => generate_stripes(w, h, seed),
        ProceduralTexturePattern::Bricks => generate_bricks(w, h, seed),
        ProceduralTexturePattern::Wood => generate_wood(w, h, seed),
        ProceduralTexturePattern::Metal => generate_metal(w, h, seed),
        ProceduralTexturePattern::Grass => generate_grass(w, h, seed),
    };

    let png_bytes = encode_png(w, h, &rgba_pixels)?;

    let now = chrono::Utc::now().to_rfc3339();
    let sidecar = serde_json::json!({
        "license": "project",
        "provenance": {
            "source": "procedural",
            "generator": "bhippi-procedural-texture",
            "pattern": format!("{pattern:?}").to_lowercase(),
            "width": w,
            "height": h,
            "seed": seed
        },
        "created_at": now,
        "attribution": "Procedurally generated by Bhippi Studio (ADR-0043)"
    });

    let sidecar_content = serde_json::to_string_pretty(&sidecar).map_err(|error| {
        EngineError::Asset(
            format!("failed to format texture sidecar: {error}"),
            Some("Report this as an engine bug.".to_owned()),
        )
    })?;

    Ok(GeneratedTexture {
        name: clean_name.to_owned(),
        rel_path,
        png_bytes,
        sidecar_content,
        width: w,
        height: h,
    })
}

/// Write the generated texture and its `.meta.json` sidecar to a project directory.
pub fn write_procedural_texture(game_dir: &Path, texture: &GeneratedTexture) -> Result<()> {
    let png_path = game_dir.join(&texture.rel_path);
    let meta_path = game_dir.join(format!("{}.meta.json", texture.rel_path));

    if let Some(parent) = png_path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| EngineError::Io {
            operation: "create_dir_all",
            path: parent.display().to_string(),
            reason: error.to_string(),
            hint: Some("Check workspace write permissions.".to_owned()),
        })?;
    }

    std::fs::write(&png_path, &texture.png_bytes).map_err(|error| EngineError::Io {
        operation: "write",
        path: png_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace disk space and permissions.".to_owned()),
    })?;

    std::fs::write(&meta_path, &texture.sidecar_content).map_err(|error| EngineError::Io {
        operation: "write",
        path: meta_path.display().to_string(),
        reason: error.to_string(),
        hint: Some("Check workspace permissions.".to_owned()),
    })?;

    Ok(())
}

fn prng(state: &mut u64) -> u32 {
    *state = state
        .wrapping_mul(6364136223846793005)
        .wrapping_add(1442695040888963407);
    ((*state >> 32) & 0xFFFFFFFF) as u32
}

fn generate_noise(w: u32, h: u32, seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            let mut state = seed
                .wrapping_add((x as u64).wrapping_mul(31))
                .wrapping_add((y as u64).wrapping_mul(373));
            let v = (prng(&mut state) % 80 + 100) as u8;
            pixels.extend_from_slice(&[v, v, v, 255]);
        }
    }
    pixels
}

fn generate_stripes(w: u32, h: u32, _seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    let stripe_width = (w / 16).max(8);
    for y in 0..h {
        for x in 0..w {
            let is_stripe = ((x + y) / stripe_width) % 2 == 0;
            if is_stripe {
                pixels.extend_from_slice(&[220, 70, 70, 255]);
            } else {
                pixels.extend_from_slice(&[240, 240, 240, 255]);
            }
        }
    }
    pixels
}

fn generate_bricks(w: u32, h: u32, seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    let brick_h = 16;
    let brick_w = 32;
    for y in 0..h {
        let row = y / brick_h;
        let is_mortar_y = y % brick_h == 0;
        let offset = if row % 2 == 1 { brick_w / 2 } else { 0 };
        for x in 0..w {
            let is_mortar_x = (x + offset) % brick_w == 0;
            if is_mortar_x || is_mortar_y {
                pixels.extend_from_slice(&[180, 180, 180, 255]);
            } else {
                let mut state = seed
                    .wrapping_add((row as u64).wrapping_mul(97))
                    .wrapping_add(((x + offset) / brick_w) as u64);
                let shade = (prng(&mut state) % 40) as u8;
                pixels.extend_from_slice(&[160 + shade, 50 + shade / 2, 40, 255]);
            }
        }
    }
    pixels
}

fn generate_wood(w: u32, h: u32, seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    let cx = (w / 2) as f32;
    let cy = (h / 2) as f32;
    for y in 0..h {
        for x in 0..w {
            let dx = (x as f32) - cx;
            let dy = (y as f32) - cy;
            let dist = (dx * dx + dy * dy).sqrt();
            let mut state = seed.wrapping_add((dist as u64).wrapping_mul(17));
            let grain = ((dist * 0.4 + (prng(&mut state) % 10) as f32).sin() * 20.0) as i16;
            let r = (140 + grain).clamp(90, 180) as u8;
            let g = (85 + grain / 2).clamp(50, 120) as u8;
            let b = (45 + grain / 3).clamp(25, 75) as u8;
            pixels.extend_from_slice(&[r, g, b, 255]);
        }
    }
    pixels
}

fn generate_metal(w: u32, h: u32, seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        let mut row_state = seed.wrapping_add((y as u64).wrapping_mul(61));
        let base_row = (prng(&mut row_state) % 30) as i16;
        for x in 0..w {
            let mut col_state = seed.wrapping_add((x as u64).wrapping_mul(13));
            let noise = (prng(&mut col_state) % 15) as i16;
            let v = (170 + base_row + noise).clamp(130, 230) as u8;
            pixels.extend_from_slice(&[v, v + 2, v + 6, 255]);
        }
    }
    pixels
}

fn generate_grass(w: u32, h: u32, seed: u64) -> Vec<u8> {
    let mut pixels = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            let mut state = seed
                .wrapping_add((x as u64).wrapping_mul(71))
                .wrapping_add((y as u64).wrapping_mul(137));
            let v = (prng(&mut state) % 60) as u8;
            let r = 35 + v / 3;
            let g = 120 + v;
            let b = 30 + v / 4;
            pixels.extend_from_slice(&[r, g, b, 255]);
        }
    }
    pixels
}

// ---------------------------------------------------------------------------
// Pure, safe, self-contained PNG encoder (RFC 2083 + RFC 1951 / 1950)
// ---------------------------------------------------------------------------

fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFFFFFF;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            let mask = (!((crc & 1) == 0)) as u32;
            crc = (crc >> 1) ^ (0xEDB88320 & (0u32.wrapping_sub(mask)));
        }
    }
    !crc
}

fn adler32(data: &[u8]) -> u32 {
    let mut s1: u32 = 1;
    let mut s2: u32 = 0;
    for &byte in data {
        s1 = (s1 + byte as u32) % 65521;
        s2 = (s2 + s1) % 65521;
    }
    (s2 << 16) | s1
}

fn encode_png(width: u32, height: u32, rgba_pixels: &[u8]) -> Result<Vec<u8>> {
    let expected_len = (width * height * 4) as usize;
    if rgba_pixels.len() != expected_len {
        return Err(EngineError::Asset(
            format!(
                "pixel buffer length {} != expected {}",
                rgba_pixels.len(),
                expected_len
            ),
            Some("Check image dimensions.".to_owned()),
        ));
    }

    let mut raw_scanlines = Vec::with_capacity(((width * 4 + 1) * height) as usize);
    let row_stride = (width * 4) as usize;
    for y in 0..height as usize {
        raw_scanlines.push(0); // Filter type 0 (None)
        let row_start = y * row_stride;
        raw_scanlines.extend_from_slice(&rgba_pixels[row_start..row_start + row_stride]);
    }

    let adler = adler32(&raw_scanlines);

    // Deflate uncompressed blocks (RFC 1951, BTYPE=00)
    let mut zlib_stream = vec![0x78, 0x01]; // zlib header (Deflate, 32K window, check bits)
    let max_block_size = 65535;
    let chunks: Vec<&[u8]> = raw_scanlines.chunks(max_block_size).collect();
    for (i, chunk) in chunks.iter().enumerate() {
        let is_last = (i == chunks.len() - 1) as u8;
        let len = chunk.len() as u16;
        let nlen = !len;
        zlib_stream.push(is_last);
        zlib_stream.extend_from_slice(&len.to_le_bytes());
        zlib_stream.extend_from_slice(&nlen.to_le_bytes());
        zlib_stream.extend_from_slice(chunk);
    }
    zlib_stream.extend_from_slice(&adler.to_be_bytes());

    let mut png = Vec::new();
    // 1. Signature
    png.extend_from_slice(&[0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A]);

    // 2. IHDR
    let mut ihdr_data = Vec::with_capacity(13);
    ihdr_data.extend_from_slice(&width.to_be_bytes());
    ihdr_data.extend_from_slice(&height.to_be_bytes());
    ihdr_data.push(8); // Bit depth: 8
    ihdr_data.push(6); // Color type: 6 (RGBA)
    ihdr_data.push(0); // Compression method: 0 (Deflate)
    ihdr_data.push(0); // Filter method: 0
    ihdr_data.push(0); // Interlace: 0
    write_chunk(&mut png, b"IHDR", &ihdr_data);

    // 3. IDAT
    write_chunk(&mut png, b"IDAT", &zlib_stream);

    // 4. IEND
    write_chunk(&mut png, b"IEND", &[]);

    Ok(png)
}

fn write_chunk(output: &mut Vec<u8>, chunk_type: &[u8; 4], data: &[u8]) {
    output.extend_from_slice(&(data.len() as u32).to_be_bytes());
    output.extend_from_slice(chunk_type);
    output.extend_from_slice(data);
    let mut crc_payload = Vec::with_capacity(4 + data.len());
    crc_payload.extend_from_slice(chunk_type);
    crc_payload.extend_from_slice(data);
    let crc = crc32(&crc_payload);
    output.extend_from_slice(&crc.to_be_bytes());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedural_texture_generates_valid_png_header_and_sidecar() {
        let texture = generate_procedural_texture(
            "CobbleGrass",
            ProceduralTexturePattern::Grass,
            64,
            64,
            123,
        )
        .unwrap();

        assert_eq!(
            &texture.png_bytes[0..8],
            &[0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A]
        );
        assert!(texture.sidecar_content.contains("\"license\": \"project\""));
        assert!(texture.sidecar_content.contains("\"pattern\": \"grass\""));
        assert_eq!(texture.width, 64);
        assert_eq!(texture.height, 64);
    }

    #[test]
    fn all_texture_patterns_bake_valid_pngs() {
        let patterns = [
            ProceduralTexturePattern::Noise,
            ProceduralTexturePattern::Stripes,
            ProceduralTexturePattern::Bricks,
            ProceduralTexturePattern::Wood,
            ProceduralTexturePattern::Metal,
            ProceduralTexturePattern::Grass,
        ];
        for pattern in patterns {
            let res = generate_procedural_texture("test", pattern, 32, 32, 42).unwrap();
            assert!(res.png_bytes.len() > 64);
            assert_eq!(&res.png_bytes[12..16], b"IHDR");
        }
    }
}
